import Foundation

/// Renders the one shell script that runs with administrator privileges.
/// Everything it does is visible in the log the app tails.
public enum FlashScript {
    public static let beginMarker = "MARYPI:BEGIN"
    public static let endMarker = "MARYPI:END"
    public static let stepMarker = "MARYPI:STEP"
    public static let errorMarker = "MARYPI:ERROR"

    public static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    public static func render(image: URL, disk: String, log: URL) throws -> String {
        let name = DiskUtil.normalize(disk)
        guard DiskUtil.isValidDiskIdentifier(name) else {
            throw MaryPiError("Refusing to flash \(disk): not a whole-disk identifier like disk4")
        }
        return """
        #!/bin/sh
        # Generated by MaryPi \(MaryPi.version). Runs once with administrator rights.
        set -u
        IMG=\(shellQuote(image.path))
        DEV=\(shellQuote(name))
        LOG=\(shellQuote(log.path))
        exec >>"$LOG" 2>&1
        fail() { echo "\(errorMarker) $1"; exit 1; }
        echo "\(beginMarker) $(date -u +%Y-%m-%dT%H:%M:%SZ) image=$IMG disk=$DEV"

        echo "\(stepMarker) unmount"
        /usr/sbin/diskutil unmountDisk force "/dev/$DEV" || fail "unmountDisk failed"

        echo "\(stepMarker) write"
        /bin/dd if="$IMG" of="/dev/r$DEV" bs=4m &
        DDPID=$!
        while /bin/kill -0 "$DDPID" 2>/dev/null; do
            /bin/kill -INFO "$DDPID" 2>/dev/null || true
            /bin/sleep 1
        done
        wait "$DDPID" || fail "dd failed"
        /bin/sync

        echo "\(stepMarker) eject"
        /usr/sbin/diskutil eject "/dev/$DEV" || fail "eject failed"
        echo "\(endMarker)"

        """
    }
}
