/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fleet.proto */

#ifndef PROTOBUF_C_fleet_2eproto__INCLUDED
#define PROTOBUF_C_fleet_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Fleet__V1__ListAdaptersRequest Fleet__V1__ListAdaptersRequest;
typedef struct Fleet__V1__ListAdaptersResponse Fleet__V1__ListAdaptersResponse;
typedef struct Fleet__V1__AdapterStatusRequest Fleet__V1__AdapterStatusRequest;
typedef struct Fleet__V1__LoRASlot Fleet__V1__LoRASlot;
typedef struct Fleet__V1__TrainingPair Fleet__V1__TrainingPair;
typedef struct Fleet__V1__TrainRequest Fleet__V1__TrainRequest;
typedef struct Fleet__V1__TrainProgress Fleet__V1__TrainProgress;
typedef struct Fleet__V1__CompleteRequest Fleet__V1__CompleteRequest;
typedef struct Fleet__V1__CompleteResponse Fleet__V1__CompleteResponse;


/* --- enums --- */


/* --- messages --- */

struct  Fleet__V1__ListAdaptersRequest
{
  ProtobufCMessage base;
  char *thread_id;
};
#define FLEET__V1__LIST_ADAPTERS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__list_adapters_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  Fleet__V1__ListAdaptersResponse
{
  ProtobufCMessage base;
  size_t n_slots;
  Fleet__V1__LoRASlot **slots;
};
#define FLEET__V1__LIST_ADAPTERS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__list_adapters_response__descriptor) \
    , 0,NULL }


struct  Fleet__V1__AdapterStatusRequest
{
  ProtobufCMessage base;
  char *thread_id;
  char *ability_id;
};
#define FLEET__V1__ADAPTER_STATUS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__adapter_status_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Fleet__V1__LoRASlot
{
  ProtobufCMessage base;
  char *ability_id;
  int32_t generation;
  int32_t pair_count;
  int64_t trained_at_unix;
  protobuf_c_boolean ready;
  char *artifact_path;
  char *cid;
  char *model_id;
  ProtobufCBinaryData schema_json;
  protobuf_c_boolean training;
};
#define FLEET__V1__LO_RASLOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__lo_raslot__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, 0 }


struct  Fleet__V1__TrainingPair
{
  ProtobufCMessage base;
  char *input_json;
  char *output_json;
};
#define FLEET__V1__TRAINING_PAIR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__training_pair__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Fleet__V1__TrainRequest
{
  ProtobufCMessage base;
  char *thread_id;
  char *ability_id;
  char *model_id;
  size_t n_pairs;
  Fleet__V1__TrainingPair **pairs;
  /*
   * Used when pairs is empty: Fleet pulls ExportCorpus from the local Thread.
   */
  char *owner_id;
  size_t n_group_ids;
  char **group_ids;
  char *document_id_prefix;
};
#define FLEET__V1__TRAIN_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__train_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, (char *)protobuf_c_empty_string, 0,NULL, (char *)protobuf_c_empty_string }


struct  Fleet__V1__TrainProgress
{
  ProtobufCMessage base;
  /*
   * preparing, loading, step, validation, finished, error
   */
  char *stage;
  int32_t iteration;
  float loss;
  char *message;
  /*
   * set on finished
   */
  Fleet__V1__LoRASlot *slot;
};
#define FLEET__V1__TRAIN_PROGRESS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__train_progress__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, NULL }


struct  Fleet__V1__CompleteRequest
{
  ProtobufCMessage base;
  char *thread_id;
  char *ability_id;
  /*
   * Optional pin: when set and it differs from the slot's current cid the
   * call is refused with the live cid, so a client refreshes its slots.
   */
  char *cid;
  char *input_json;
};
#define FLEET__V1__COMPLETE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__complete_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Fleet__V1__CompleteResponse
{
  ProtobufCMessage base;
  char *output_json;
  char *raw_text;
  double forced_fraction;
  int32_t prompt_tokens;
  char *cid;
};
#define FLEET__V1__COMPLETE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fleet__v1__complete_response__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string }


/* Fleet__V1__ListAdaptersRequest methods */
void   fleet__v1__list_adapters_request__init
                     (Fleet__V1__ListAdaptersRequest         *message);
size_t fleet__v1__list_adapters_request__get_packed_size
                     (const Fleet__V1__ListAdaptersRequest   *message);
size_t fleet__v1__list_adapters_request__pack
                     (const Fleet__V1__ListAdaptersRequest   *message,
                      uint8_t             *out);
size_t fleet__v1__list_adapters_request__pack_to_buffer
                     (const Fleet__V1__ListAdaptersRequest   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__ListAdaptersRequest *
       fleet__v1__list_adapters_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__list_adapters_request__free_unpacked
                     (Fleet__V1__ListAdaptersRequest *message,
                      ProtobufCAllocator *allocator);
/* Fleet__V1__ListAdaptersResponse methods */
void   fleet__v1__list_adapters_response__init
                     (Fleet__V1__ListAdaptersResponse         *message);
size_t fleet__v1__list_adapters_response__get_packed_size
                     (const Fleet__V1__ListAdaptersResponse   *message);
size_t fleet__v1__list_adapters_response__pack
                     (const Fleet__V1__ListAdaptersResponse   *message,
                      uint8_t             *out);
size_t fleet__v1__list_adapters_response__pack_to_buffer
                     (const Fleet__V1__ListAdaptersResponse   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__ListAdaptersResponse *
       fleet__v1__list_adapters_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__list_adapters_response__free_unpacked
                     (Fleet__V1__ListAdaptersResponse *message,
                      ProtobufCAllocator *allocator);
/* Fleet__V1__AdapterStatusRequest methods */
void   fleet__v1__adapter_status_request__init
                     (Fleet__V1__AdapterStatusRequest         *message);
size_t fleet__v1__adapter_status_request__get_packed_size
                     (const Fleet__V1__AdapterStatusRequest   *message);
size_t fleet__v1__adapter_status_request__pack
                     (const Fleet__V1__AdapterStatusRequest   *message,
                      uint8_t             *out);
size_t fleet__v1__adapter_status_request__pack_to_buffer
                     (const Fleet__V1__AdapterStatusRequest   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__AdapterStatusRequest *
       fleet__v1__adapter_status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__adapter_status_request__free_unpacked
                     (Fleet__V1__AdapterStatusRequest *message,
                      ProtobufCAllocator *allocator);
/* Fleet__V1__LoRASlot methods */
void   fleet__v1__lo_raslot__init
                     (Fleet__V1__LoRASlot         *message);
size_t fleet__v1__lo_raslot__get_packed_size
                     (const Fleet__V1__LoRASlot   *message);
size_t fleet__v1__lo_raslot__pack
                     (const Fleet__V1__LoRASlot   *message,
                      uint8_t             *out);
size_t fleet__v1__lo_raslot__pack_to_buffer
                     (const Fleet__V1__LoRASlot   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__LoRASlot *
       fleet__v1__lo_raslot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__lo_raslot__free_unpacked
                     (Fleet__V1__LoRASlot *message,
                      ProtobufCAllocator *allocator);
/* Fleet__V1__TrainingPair methods */
void   fleet__v1__training_pair__init
                     (Fleet__V1__TrainingPair         *message);
size_t fleet__v1__training_pair__get_packed_size
                     (const Fleet__V1__TrainingPair   *message);
size_t fleet__v1__training_pair__pack
                     (const Fleet__V1__TrainingPair   *message,
                      uint8_t             *out);
size_t fleet__v1__training_pair__pack_to_buffer
                     (const Fleet__V1__TrainingPair   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__TrainingPair *
       fleet__v1__training_pair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__training_pair__free_unpacked
                     (Fleet__V1__TrainingPair *message,
                      ProtobufCAllocator *allocator);
/* Fleet__V1__TrainRequest methods */
void   fleet__v1__train_request__init
                     (Fleet__V1__TrainRequest         *message);
size_t fleet__v1__train_request__get_packed_size
                     (const Fleet__V1__TrainRequest   *message);
size_t fleet__v1__train_request__pack
                     (const Fleet__V1__TrainRequest   *message,
                      uint8_t             *out);
size_t fleet__v1__train_request__pack_to_buffer
                     (const Fleet__V1__TrainRequest   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__TrainRequest *
       fleet__v1__train_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__train_request__free_unpacked
                     (Fleet__V1__TrainRequest *message,
                      ProtobufCAllocator *allocator);
/* Fleet__V1__TrainProgress methods */
void   fleet__v1__train_progress__init
                     (Fleet__V1__TrainProgress         *message);
size_t fleet__v1__train_progress__get_packed_size
                     (const Fleet__V1__TrainProgress   *message);
size_t fleet__v1__train_progress__pack
                     (const Fleet__V1__TrainProgress   *message,
                      uint8_t             *out);
size_t fleet__v1__train_progress__pack_to_buffer
                     (const Fleet__V1__TrainProgress   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__TrainProgress *
       fleet__v1__train_progress__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__train_progress__free_unpacked
                     (Fleet__V1__TrainProgress *message,
                      ProtobufCAllocator *allocator);
/* Fleet__V1__CompleteRequest methods */
void   fleet__v1__complete_request__init
                     (Fleet__V1__CompleteRequest         *message);
size_t fleet__v1__complete_request__get_packed_size
                     (const Fleet__V1__CompleteRequest   *message);
size_t fleet__v1__complete_request__pack
                     (const Fleet__V1__CompleteRequest   *message,
                      uint8_t             *out);
size_t fleet__v1__complete_request__pack_to_buffer
                     (const Fleet__V1__CompleteRequest   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__CompleteRequest *
       fleet__v1__complete_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__complete_request__free_unpacked
                     (Fleet__V1__CompleteRequest *message,
                      ProtobufCAllocator *allocator);
/* Fleet__V1__CompleteResponse methods */
void   fleet__v1__complete_response__init
                     (Fleet__V1__CompleteResponse         *message);
size_t fleet__v1__complete_response__get_packed_size
                     (const Fleet__V1__CompleteResponse   *message);
size_t fleet__v1__complete_response__pack
                     (const Fleet__V1__CompleteResponse   *message,
                      uint8_t             *out);
size_t fleet__v1__complete_response__pack_to_buffer
                     (const Fleet__V1__CompleteResponse   *message,
                      ProtobufCBuffer     *buffer);
Fleet__V1__CompleteResponse *
       fleet__v1__complete_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fleet__v1__complete_response__free_unpacked
                     (Fleet__V1__CompleteResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fleet__V1__ListAdaptersRequest_Closure)
                 (const Fleet__V1__ListAdaptersRequest *message,
                  void *closure_data);
typedef void (*Fleet__V1__ListAdaptersResponse_Closure)
                 (const Fleet__V1__ListAdaptersResponse *message,
                  void *closure_data);
typedef void (*Fleet__V1__AdapterStatusRequest_Closure)
                 (const Fleet__V1__AdapterStatusRequest *message,
                  void *closure_data);
typedef void (*Fleet__V1__LoRASlot_Closure)
                 (const Fleet__V1__LoRASlot *message,
                  void *closure_data);
typedef void (*Fleet__V1__TrainingPair_Closure)
                 (const Fleet__V1__TrainingPair *message,
                  void *closure_data);
typedef void (*Fleet__V1__TrainRequest_Closure)
                 (const Fleet__V1__TrainRequest *message,
                  void *closure_data);
typedef void (*Fleet__V1__TrainProgress_Closure)
                 (const Fleet__V1__TrainProgress *message,
                  void *closure_data);
typedef void (*Fleet__V1__CompleteRequest_Closure)
                 (const Fleet__V1__CompleteRequest *message,
                  void *closure_data);
typedef void (*Fleet__V1__CompleteResponse_Closure)
                 (const Fleet__V1__CompleteResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct Fleet__V1__FleetLoRA_Service Fleet__V1__FleetLoRA_Service;
struct Fleet__V1__FleetLoRA_Service
{
  ProtobufCService base;
  void (*list_adapters)(Fleet__V1__FleetLoRA_Service *service,
                        const Fleet__V1__ListAdaptersRequest *input,
                        Fleet__V1__ListAdaptersResponse_Closure closure,
                        void *closure_data);
  void (*adapter_status)(Fleet__V1__FleetLoRA_Service *service,
                         const Fleet__V1__AdapterStatusRequest *input,
                         Fleet__V1__LoRASlot_Closure closure,
                         void *closure_data);
  void (*train)(Fleet__V1__FleetLoRA_Service *service,
                const Fleet__V1__TrainRequest *input,
                Fleet__V1__TrainProgress_Closure closure,
                void *closure_data);
  void (*complete)(Fleet__V1__FleetLoRA_Service *service,
                   const Fleet__V1__CompleteRequest *input,
                   Fleet__V1__CompleteResponse_Closure closure,
                   void *closure_data);
};
typedef void (*Fleet__V1__FleetLoRA_ServiceDestroy)(Fleet__V1__FleetLoRA_Service *);
void fleet__v1__fleet_lo_ra__init (Fleet__V1__FleetLoRA_Service *service,
                                   Fleet__V1__FleetLoRA_ServiceDestroy destroy);
#define FLEET__V1__FLEET_LO_RA__BASE_INIT \
    { &fleet__v1__fleet_lo_ra__descriptor, protobuf_c_service_invoke_internal, NULL }
#define FLEET__V1__FLEET_LO_RA__INIT(function_prefix__) \
    { FLEET__V1__FLEET_LO_RA__BASE_INIT,\
      function_prefix__ ## list_adapters,\
      function_prefix__ ## adapter_status,\
      function_prefix__ ## train,\
      function_prefix__ ## complete  }
void fleet__v1__fleet_lo_ra__list_adapters(ProtobufCService *service,
                                           const Fleet__V1__ListAdaptersRequest *input,
                                           Fleet__V1__ListAdaptersResponse_Closure closure,
                                           void *closure_data);
void fleet__v1__fleet_lo_ra__adapter_status(ProtobufCService *service,
                                            const Fleet__V1__AdapterStatusRequest *input,
                                            Fleet__V1__LoRASlot_Closure closure,
                                            void *closure_data);
void fleet__v1__fleet_lo_ra__train(ProtobufCService *service,
                                   const Fleet__V1__TrainRequest *input,
                                   Fleet__V1__TrainProgress_Closure closure,
                                   void *closure_data);
void fleet__v1__fleet_lo_ra__complete(ProtobufCService *service,
                                      const Fleet__V1__CompleteRequest *input,
                                      Fleet__V1__CompleteResponse_Closure closure,
                                      void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fleet__v1__list_adapters_request__descriptor;
extern const ProtobufCMessageDescriptor fleet__v1__list_adapters_response__descriptor;
extern const ProtobufCMessageDescriptor fleet__v1__adapter_status_request__descriptor;
extern const ProtobufCMessageDescriptor fleet__v1__lo_raslot__descriptor;
extern const ProtobufCMessageDescriptor fleet__v1__training_pair__descriptor;
extern const ProtobufCMessageDescriptor fleet__v1__train_request__descriptor;
extern const ProtobufCMessageDescriptor fleet__v1__train_progress__descriptor;
extern const ProtobufCMessageDescriptor fleet__v1__complete_request__descriptor;
extern const ProtobufCMessageDescriptor fleet__v1__complete_response__descriptor;
extern const ProtobufCServiceDescriptor fleet__v1__fleet_lo_ra__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_fleet_2eproto__INCLUDED */
