/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: thread.proto */

#ifndef PROTOBUF_C_thread_2eproto__INCLUDED
#define PROTOBUF_C_thread_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Thread__V1__RegisterRequest Thread__V1__RegisterRequest;
typedef struct Thread__V1__RegisterResponse Thread__V1__RegisterResponse;
typedef struct Thread__V1__HeartbeatRequest Thread__V1__HeartbeatRequest;
typedef struct Thread__V1__HeartbeatResponse Thread__V1__HeartbeatResponse;
typedef struct Thread__V1__AvailabilityUpdateRequest Thread__V1__AvailabilityUpdateRequest;
typedef struct Thread__V1__AvailabilityUpdateResponse Thread__V1__AvailabilityUpdateResponse;
typedef struct Thread__V1__ThreadSearchRequest Thread__V1__ThreadSearchRequest;
typedef struct Thread__V1__ThreadSearchResponse Thread__V1__ThreadSearchResponse;
typedef struct Thread__V1__ThreadGraphTrace Thread__V1__ThreadGraphTrace;
typedef struct Thread__V1__ThreadPartitionResult Thread__V1__ThreadPartitionResult;
typedef struct Thread__V1__ThreadIndexRequest Thread__V1__ThreadIndexRequest;
typedef struct Thread__V1__ThreadIndexItem Thread__V1__ThreadIndexItem;
typedef struct Thread__V1__ThreadGraphEntityIn Thread__V1__ThreadGraphEntityIn;
typedef struct Thread__V1__ThreadGraphRelationIn Thread__V1__ThreadGraphRelationIn;
typedef struct Thread__V1__ThreadIndexResponse Thread__V1__ThreadIndexResponse;
typedef struct Thread__V1__ThreadRemoveRequest Thread__V1__ThreadRemoveRequest;
typedef struct Thread__V1__ThreadRemoveResponse Thread__V1__ThreadRemoveResponse;
typedef struct Thread__V1__ThreadUpdateGroupRequest Thread__V1__ThreadUpdateGroupRequest;
typedef struct Thread__V1__ThreadUpdateGroupResponse Thread__V1__ThreadUpdateGroupResponse;
typedef struct Thread__V1__ThreadUpdateDocumentRequest Thread__V1__ThreadUpdateDocumentRequest;
typedef struct Thread__V1__ThreadUpdateDocumentResponse Thread__V1__ThreadUpdateDocumentResponse;
typedef struct Thread__V1__ThreadStatsRequest Thread__V1__ThreadStatsRequest;
typedef struct Thread__V1__ThreadStatsResponse Thread__V1__ThreadStatsResponse;
typedef struct Thread__V1__ThreadDocument Thread__V1__ThreadDocument;
typedef struct Thread__V1__ThreadGroup Thread__V1__ThreadGroup;
typedef struct Thread__V1__ThreadLibraryRequest Thread__V1__ThreadLibraryRequest;
typedef struct Thread__V1__ThreadLibraryResponse Thread__V1__ThreadLibraryResponse;
typedef struct Thread__V1__ThreadDocumentsRequest Thread__V1__ThreadDocumentsRequest;
typedef struct Thread__V1__ThreadDocumentContent Thread__V1__ThreadDocumentContent;
typedef struct Thread__V1__ThreadDocumentsResponse Thread__V1__ThreadDocumentsResponse;
typedef struct Thread__V1__ThreadExportCorpusRequest Thread__V1__ThreadExportCorpusRequest;
typedef struct Thread__V1__ThreadExportCorpusResponse Thread__V1__ThreadExportCorpusResponse;
typedef struct Thread__V1__ThreadGraphQueryRequest Thread__V1__ThreadGraphQueryRequest;
typedef struct Thread__V1__ThreadGraphEntity Thread__V1__ThreadGraphEntity;
typedef struct Thread__V1__ThreadGraphRelationship Thread__V1__ThreadGraphRelationship;
typedef struct Thread__V1__ThreadGraphDocument Thread__V1__ThreadGraphDocument;
typedef struct Thread__V1__ThreadGraphStats Thread__V1__ThreadGraphStats;
typedef struct Thread__V1__ThreadGraphQueryResponse Thread__V1__ThreadGraphQueryResponse;
typedef struct Thread__V1__ThreadSessionMessage Thread__V1__ThreadSessionMessage;
typedef struct Thread__V1__ThreadSessionPing Thread__V1__ThreadSessionPing;
typedef struct Thread__V1__ThreadSessionPong Thread__V1__ThreadSessionPong;


/* --- enums --- */


/* --- messages --- */

struct  Thread__V1__RegisterRequest
{
  ProtobufCMessage base;
  char *thread_id;
  char *host;
  int32_t grpc_port;
  /*
   * Thread's HTTP/REST port (for proxy forwarding)
   */
  int32_t http_port;
};
#define THREAD__V1__REGISTER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__register_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


struct  Thread__V1__RegisterResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean accepted;
  char *mothership_id;
};
#define THREAD__V1__REGISTER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__register_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  Thread__V1__HeartbeatRequest
{
  ProtobufCMessage base;
  char *thread_id;
};
#define THREAD__V1__HEARTBEAT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__heartbeat_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  Thread__V1__HeartbeatResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean alive;
};
#define THREAD__V1__HEARTBEAT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__heartbeat_response__descriptor) \
    , 0 }


struct  Thread__V1__AvailabilityUpdateRequest
{
  ProtobufCMessage base;
  char *thread_id;
  protobuf_c_boolean accepting_storage;
};
#define THREAD__V1__AVAILABILITY_UPDATE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__availability_update_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Thread__V1__AvailabilityUpdateResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean acknowledged;
};
#define THREAD__V1__AVAILABILITY_UPDATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__availability_update_response__descriptor) \
    , 0 }


struct  Thread__V1__ThreadSearchRequest
{
  ProtobufCMessage base;
  size_t n_query_embedding;
  float *query_embedding;
  /*
   * was query_tag_embedding (same wire format)
   */
  size_t n_query_entity_embedding;
  float *query_entity_embedding;
  char *owner_id;
  char *scope;
  int32_t top_k;
  size_t n_group_ids;
  char **group_ids;
  protobuf_c_boolean aggregate;
  /*
   * raw query; Thread embeds if query_embedding is empty
   */
  char *query_text;
  /*
   * query entity terms for graph matching
   */
  size_t n_entities;
  char **entities;
};
#define THREAD__V1__THREAD_SEARCH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_search_request__descriptor) \
    , 0,NULL, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0,NULL, 0, (char *)protobuf_c_empty_string, 0,NULL }


struct  Thread__V1__ThreadSearchResponse
{
  ProtobufCMessage base;
  size_t n_results;
  Thread__V1__ThreadPartitionResult **results;
  /*
   * how the knowledge graph shaped this search
   */
  Thread__V1__ThreadGraphTrace *trace;
};
#define THREAD__V1__THREAD_SEARCH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_search_response__descriptor) \
    , 0,NULL, NULL }


/*
 * Graph provenance for a hybrid search: which entities matched the query and
 * which edges pulled in extra documents during one-hop expansion.
 */
struct  Thread__V1__ThreadGraphTrace
{
  ProtobufCMessage base;
  size_t n_matched_entity_ids;
  char **matched_entity_ids;
  size_t n_expansion_edge_ids;
  char **expansion_edge_ids;
  int32_t expanded_document_count;
};
#define THREAD__V1__THREAD_GRAPH_TRACE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_trace__descriptor) \
    , 0,NULL, 0,NULL, 0 }


struct  Thread__V1__ThreadPartitionResult
{
  ProtobufCMessage base;
  char *thread_id;
  char *partition_id;
  char *document_id;
  char *owner_id;
  char *text;
  float score;
  /*
   * always 0; shards retired with HNSW
   */
  int32_t shard_index PROTOBUF_C__DEPRECATED;
};
#define THREAD__V1__THREAD_PARTITION_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_partition_result__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


struct  Thread__V1__ThreadIndexRequest
{
  ProtobufCMessage base;
  char *owner_id;
  char *group_id;
  char *group_label;
  char *scope;
  size_t n_items;
  Thread__V1__ThreadIndexItem **items;
};
#define THREAD__V1__THREAD_INDEX_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_index_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Thread__V1__ThreadIndexItem
{
  ProtobufCMessage base;
  char *document_id;
  size_t n_texts;
  char **texts;
  /*
   * legacy: treated as concept entities when entities is empty
   */
  size_t n_tags;
  char **tags;
  char *name;
  ProtobufCBinaryData metadata;
  char *media_type;
  /*
   * caller-provided graph payload (optional;
   */
  size_t n_entities;
  Thread__V1__ThreadGraphEntityIn **entities;
  /*
   * Thread extracts when both are empty)
   */
  size_t n_relationships;
  Thread__V1__ThreadGraphRelationIn **relationships;
};
#define THREAD__V1__THREAD_INDEX_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_index_item__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL }


struct  Thread__V1__ThreadGraphEntityIn
{
  ProtobufCMessage base;
  char *name;
  /*
   * person|organization|place|event|work|concept|other; "" = concept
   */
  char *kind;
};
#define THREAD__V1__THREAD_GRAPH_ENTITY_IN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_entity_in__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Thread__V1__ThreadGraphRelationIn
{
  ProtobufCMessage base;
  char *subject;
  char *predicate;
  char *object;
};
#define THREAD__V1__THREAD_GRAPH_RELATION_IN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_relation_in__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Thread__V1__ThreadIndexResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
  int32_t indexed_count;
  size_t n_full_cids;
  char **full_cids;
};
#define THREAD__V1__THREAD_INDEX_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_index_response__descriptor) \
    , 0, 0, 0,NULL }


struct  Thread__V1__ThreadRemoveRequest
{
  ProtobufCMessage base;
  char *owner_id;
  size_t n_document_ids;
  char **document_ids;
};
#define THREAD__V1__THREAD_REMOVE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_remove_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  Thread__V1__ThreadRemoveResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
  int32_t removed_count;
};
#define THREAD__V1__THREAD_REMOVE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_remove_response__descriptor) \
    , 0, 0 }


struct  Thread__V1__ThreadUpdateGroupRequest
{
  ProtobufCMessage base;
  char *owner_id;
  char *group_id;
  /*
   * "available" | "restricted" | "" (no change)
   */
  char *access;
  /*
   * "" = no change
   */
  char *label;
  /*
   * only applied when update_metadata = true
   */
  char *group_description;
  /*
   * only applied when update_metadata = true
   */
  size_t n_tags;
  char **tags;
  /*
   * when true, replaces description + tags
   */
  protobuf_c_boolean update_metadata;
};
#define THREAD__V1__THREAD_UPDATE_GROUP_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_update_group_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0 }


struct  Thread__V1__ThreadUpdateGroupResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
  char *group_id;
};
#define THREAD__V1__THREAD_UPDATE_GROUP_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_update_group_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  Thread__V1__ThreadUpdateDocumentRequest
{
  ProtobufCMessage base;
  char *owner_id;
  char *document_id;
  /*
   * "available" | "restricted" | "" (no change)
   */
  char *access;
  /*
   * move to this group; "" = no change
   */
  char *group_id;
};
#define THREAD__V1__THREAD_UPDATE_DOCUMENT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_update_document_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Thread__V1__ThreadUpdateDocumentResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
  char *document_id;
};
#define THREAD__V1__THREAD_UPDATE_DOCUMENT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_update_document_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  Thread__V1__ThreadStatsRequest
{
  ProtobufCMessage base;
};
#define THREAD__V1__THREAD_STATS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_stats_request__descriptor) \
     }


struct  Thread__V1__ThreadStatsResponse
{
  ProtobufCMessage base;
  int64_t document_count;
  int64_t group_count;
  int64_t owner_count;
  int64_t available_document_count;
};
#define THREAD__V1__THREAD_STATS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_stats_response__descriptor) \
    , 0, 0, 0, 0 }


struct  Thread__V1__ThreadDocument
{
  ProtobufCMessage base;
  char *id;
  char *url;
  char *owner_id;
  char *name;
  int64_t created_at;
};
#define THREAD__V1__THREAD_DOCUMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_document__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Thread__V1__ThreadGroup
{
  ProtobufCMessage base;
  char *id;
  char *label;
  char *owner_id;
  size_t n_documents;
  Thread__V1__ThreadDocument **documents;
  char *access;
  double total_earnings;
  char *group_description;
  size_t n_tags;
  char **tags;
};
#define THREAD__V1__THREAD_GROUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_group__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0,NULL }


struct  Thread__V1__ThreadLibraryRequest
{
  ProtobufCMessage base;
  char *owner_id;
  protobuf_c_boolean include_available;
  /*
   * 0 = no limit (return all)
   */
  int32_t limit;
  /*
   * cursor: return groups with id > after_id (sorted); empty = start
   */
  char *after_id;
  /*
   * UUID of this Thread node; set by Sewn for logging/validation
   */
  char *thread_id;
  /*
   * when non-empty, filter to groups containing these docs
   */
  size_t n_document_ids;
  char **document_ids;
};
#define THREAD__V1__THREAD_LIBRARY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_library_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Thread__V1__ThreadLibraryResponse
{
  ProtobufCMessage base;
  size_t n_groups;
  Thread__V1__ThreadGroup **groups;
  /*
   * true if more pages follow
   */
  protobuf_c_boolean has_more;
};
#define THREAD__V1__THREAD_LIBRARY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_library_response__descriptor) \
    , 0,NULL, 0 }


struct  Thread__V1__ThreadDocumentsRequest
{
  ProtobufCMessage base;
  char *owner_id;
  size_t n_document_ids;
  char **document_ids;
};
#define THREAD__V1__THREAD_DOCUMENTS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_documents_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  Thread__V1__ThreadDocumentContent
{
  ProtobufCMessage base;
  char *id;
  char *name;
  char *owner_id;
  char *group_id;
  char *group_label;
  int64_t created_at;
  /*
   * partition texts in stored order; join for full content
   */
  size_t n_texts;
  char **texts;
  char *media_type;
};
#define THREAD__V1__THREAD_DOCUMENT_CONTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_document_content__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0,NULL, (char *)protobuf_c_empty_string }


struct  Thread__V1__ThreadDocumentsResponse
{
  ProtobufCMessage base;
  /*
   * inaccessible/unknown ids omitted
   */
  size_t n_documents;
  Thread__V1__ThreadDocumentContent **documents;
};
#define THREAD__V1__THREAD_DOCUMENTS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_documents_response__descriptor) \
    , 0,NULL }


struct  Thread__V1__ThreadExportCorpusRequest
{
  ProtobufCMessage base;
  char *owner_id;
  /*
   * empty = every group the owner can read
   */
  size_t n_group_ids;
  char **group_ids;
  /*
   * e.g. "mary-behavior-"; empty = any
   */
  char *document_id_prefix;
  /*
   * exclusive cursor on sorted document id
   */
  char *after_id;
  /*
   * 0 = no limit
   */
  int32_t limit;
};
#define THREAD__V1__THREAD_EXPORT_CORPUS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_export_corpus_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Thread__V1__ThreadExportCorpusResponse
{
  ProtobufCMessage base;
  size_t n_documents;
  Thread__V1__ThreadDocumentContent **documents;
  protobuf_c_boolean has_more;
};
#define THREAD__V1__THREAD_EXPORT_CORPUS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_export_corpus_response__descriptor) \
    , 0,NULL, 0 }


/*
 * entity: exact/token entity name to match; query: free text (Thread embeds it)
 * At least one of entity/query should be set. hops 0–3 (BFS depth from matches).
 */
struct  Thread__V1__ThreadGraphQueryRequest
{
  ProtobufCMessage base;
  char *owner_id;
  char *entity;
  char *query;
  size_t n_kinds;
  char **kinds;
  int32_t hops;
  /*
   * 0 = default
   */
  int32_t limit;
  protobuf_c_boolean include_documents;
};
#define THREAD__V1__THREAD_GRAPH_QUERY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_query_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0, 0, 0 }


struct  Thread__V1__ThreadGraphEntity
{
  ProtobufCMessage base;
  char *id;
  char *name;
  char *kind;
  /*
   * match score for seed entities; 0 for neighbors
   */
  float score;
  int32_t mention_count;
  size_t n_document_ids;
  char **document_ids;
};
#define THREAD__V1__THREAD_GRAPH_ENTITY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_entity__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0,NULL }


struct  Thread__V1__ThreadGraphRelationship
{
  ProtobufCMessage base;
  char *id;
  char *subject_id;
  char *predicate;
  char *object_id;
  int32_t weight;
  size_t n_document_ids;
  char **document_ids;
};
#define THREAD__V1__THREAD_GRAPH_RELATIONSHIP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_relationship__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0,NULL }


struct  Thread__V1__ThreadGraphDocument
{
  ProtobufCMessage base;
  char *id;
  char *name;
  char *owner_id;
};
#define THREAD__V1__THREAD_GRAPH_DOCUMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_document__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Thread__V1__ThreadGraphStats
{
  ProtobufCMessage base;
  int64_t entity_count;
  int64_t relationship_count;
};
#define THREAD__V1__THREAD_GRAPH_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_stats__descriptor) \
    , 0, 0 }


struct  Thread__V1__ThreadGraphQueryResponse
{
  ProtobufCMessage base;
  size_t n_entities;
  Thread__V1__ThreadGraphEntity **entities;
  size_t n_relationships;
  Thread__V1__ThreadGraphRelationship **relationships;
  size_t n_documents;
  Thread__V1__ThreadGraphDocument **documents;
  Thread__V1__ThreadGraphStats *stats;
};
#define THREAD__V1__THREAD_GRAPH_QUERY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_graph_query_response__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, NULL }


typedef enum {
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD__NOT_SET = 0,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_PING = 3,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_PONG = 4,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_SEARCH_REQUEST = 5,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_SEARCH_RESPONSE = 6,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_INDEX_REQUEST = 7,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_INDEX_RESPONSE = 8,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_REMOVE_REQUEST = 9,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_REMOVE_RESPONSE = 10,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_LIBRARY_REQUEST = 11,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_LIBRARY_RESPONSE = 12,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_UPDATE_GROUP_REQUEST = 23,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_UPDATE_GROUP_RESPONSE = 24,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_UPDATE_DOCUMENT_REQUEST = 25,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_UPDATE_DOCUMENT_RESPONSE = 26,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_STATS_REQUEST = 27,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_STATS_RESPONSE = 28,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_GRAPH_REQUEST = 29,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_GRAPH_RESPONSE = 30,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_DOCUMENTS_REQUEST = 31,
  THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD_DOCUMENTS_RESPONSE = 32
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD__CASE)
} Thread__V1__ThreadSessionMessage__PayloadCase;

/*
 * ── Session envelope — used by the bidirectional Session RPC ─────────────────
 * Thread sends pings and response payloads; Sewn sends request payloads.
 * correlation_id ties each request to its response.
 * thread_id is set by Thread on every Ping so Sewn can identify the stream.
 */
struct  Thread__V1__ThreadSessionMessage
{
  ProtobufCMessage base;
  char *correlation_id;
  char *thread_id;
  Thread__V1__ThreadSessionMessage__PayloadCase payload_case;
  union {
    Thread__V1__ThreadSessionPing *ping;
    Thread__V1__ThreadSessionPong *pong;
    Thread__V1__ThreadSearchRequest *search_request;
    Thread__V1__ThreadSearchResponse *search_response;
    Thread__V1__ThreadIndexRequest *index_request;
    Thread__V1__ThreadIndexResponse *index_response;
    Thread__V1__ThreadRemoveRequest *remove_request;
    Thread__V1__ThreadRemoveResponse *remove_response;
    Thread__V1__ThreadLibraryRequest *library_request;
    Thread__V1__ThreadLibraryResponse *library_response;
    Thread__V1__ThreadUpdateGroupRequest *update_group_request;
    Thread__V1__ThreadUpdateGroupResponse *update_group_response;
    Thread__V1__ThreadUpdateDocumentRequest *update_document_request;
    Thread__V1__ThreadUpdateDocumentResponse *update_document_response;
    Thread__V1__ThreadStatsRequest *stats_request;
    Thread__V1__ThreadStatsResponse *stats_response;
    Thread__V1__ThreadGraphQueryRequest *graph_request;
    Thread__V1__ThreadGraphQueryResponse *graph_response;
    Thread__V1__ThreadDocumentsRequest *documents_request;
    Thread__V1__ThreadDocumentsResponse *documents_response;
  };
};
#define THREAD__V1__THREAD_SESSION_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_session_message__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, THREAD__V1__THREAD_SESSION_MESSAGE__PAYLOAD__NOT_SET, {0} }


struct  Thread__V1__ThreadSessionPing
{
  ProtobufCMessage base;
};
#define THREAD__V1__THREAD_SESSION_PING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_session_ping__descriptor) \
     }


struct  Thread__V1__ThreadSessionPong
{
  ProtobufCMessage base;
};
#define THREAD__V1__THREAD_SESSION_PONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread__v1__thread_session_pong__descriptor) \
     }


/* Thread__V1__RegisterRequest methods */
void   thread__v1__register_request__init
                     (Thread__V1__RegisterRequest         *message);
size_t thread__v1__register_request__get_packed_size
                     (const Thread__V1__RegisterRequest   *message);
size_t thread__v1__register_request__pack
                     (const Thread__V1__RegisterRequest   *message,
                      uint8_t             *out);
size_t thread__v1__register_request__pack_to_buffer
                     (const Thread__V1__RegisterRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__RegisterRequest *
       thread__v1__register_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__register_request__free_unpacked
                     (Thread__V1__RegisterRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__RegisterResponse methods */
void   thread__v1__register_response__init
                     (Thread__V1__RegisterResponse         *message);
size_t thread__v1__register_response__get_packed_size
                     (const Thread__V1__RegisterResponse   *message);
size_t thread__v1__register_response__pack
                     (const Thread__V1__RegisterResponse   *message,
                      uint8_t             *out);
size_t thread__v1__register_response__pack_to_buffer
                     (const Thread__V1__RegisterResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__RegisterResponse *
       thread__v1__register_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__register_response__free_unpacked
                     (Thread__V1__RegisterResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__HeartbeatRequest methods */
void   thread__v1__heartbeat_request__init
                     (Thread__V1__HeartbeatRequest         *message);
size_t thread__v1__heartbeat_request__get_packed_size
                     (const Thread__V1__HeartbeatRequest   *message);
size_t thread__v1__heartbeat_request__pack
                     (const Thread__V1__HeartbeatRequest   *message,
                      uint8_t             *out);
size_t thread__v1__heartbeat_request__pack_to_buffer
                     (const Thread__V1__HeartbeatRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__HeartbeatRequest *
       thread__v1__heartbeat_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__heartbeat_request__free_unpacked
                     (Thread__V1__HeartbeatRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__HeartbeatResponse methods */
void   thread__v1__heartbeat_response__init
                     (Thread__V1__HeartbeatResponse         *message);
size_t thread__v1__heartbeat_response__get_packed_size
                     (const Thread__V1__HeartbeatResponse   *message);
size_t thread__v1__heartbeat_response__pack
                     (const Thread__V1__HeartbeatResponse   *message,
                      uint8_t             *out);
size_t thread__v1__heartbeat_response__pack_to_buffer
                     (const Thread__V1__HeartbeatResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__HeartbeatResponse *
       thread__v1__heartbeat_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__heartbeat_response__free_unpacked
                     (Thread__V1__HeartbeatResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__AvailabilityUpdateRequest methods */
void   thread__v1__availability_update_request__init
                     (Thread__V1__AvailabilityUpdateRequest         *message);
size_t thread__v1__availability_update_request__get_packed_size
                     (const Thread__V1__AvailabilityUpdateRequest   *message);
size_t thread__v1__availability_update_request__pack
                     (const Thread__V1__AvailabilityUpdateRequest   *message,
                      uint8_t             *out);
size_t thread__v1__availability_update_request__pack_to_buffer
                     (const Thread__V1__AvailabilityUpdateRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__AvailabilityUpdateRequest *
       thread__v1__availability_update_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__availability_update_request__free_unpacked
                     (Thread__V1__AvailabilityUpdateRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__AvailabilityUpdateResponse methods */
void   thread__v1__availability_update_response__init
                     (Thread__V1__AvailabilityUpdateResponse         *message);
size_t thread__v1__availability_update_response__get_packed_size
                     (const Thread__V1__AvailabilityUpdateResponse   *message);
size_t thread__v1__availability_update_response__pack
                     (const Thread__V1__AvailabilityUpdateResponse   *message,
                      uint8_t             *out);
size_t thread__v1__availability_update_response__pack_to_buffer
                     (const Thread__V1__AvailabilityUpdateResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__AvailabilityUpdateResponse *
       thread__v1__availability_update_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__availability_update_response__free_unpacked
                     (Thread__V1__AvailabilityUpdateResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadSearchRequest methods */
void   thread__v1__thread_search_request__init
                     (Thread__V1__ThreadSearchRequest         *message);
size_t thread__v1__thread_search_request__get_packed_size
                     (const Thread__V1__ThreadSearchRequest   *message);
size_t thread__v1__thread_search_request__pack
                     (const Thread__V1__ThreadSearchRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_search_request__pack_to_buffer
                     (const Thread__V1__ThreadSearchRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadSearchRequest *
       thread__v1__thread_search_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_search_request__free_unpacked
                     (Thread__V1__ThreadSearchRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadSearchResponse methods */
void   thread__v1__thread_search_response__init
                     (Thread__V1__ThreadSearchResponse         *message);
size_t thread__v1__thread_search_response__get_packed_size
                     (const Thread__V1__ThreadSearchResponse   *message);
size_t thread__v1__thread_search_response__pack
                     (const Thread__V1__ThreadSearchResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_search_response__pack_to_buffer
                     (const Thread__V1__ThreadSearchResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadSearchResponse *
       thread__v1__thread_search_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_search_response__free_unpacked
                     (Thread__V1__ThreadSearchResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphTrace methods */
void   thread__v1__thread_graph_trace__init
                     (Thread__V1__ThreadGraphTrace         *message);
size_t thread__v1__thread_graph_trace__get_packed_size
                     (const Thread__V1__ThreadGraphTrace   *message);
size_t thread__v1__thread_graph_trace__pack
                     (const Thread__V1__ThreadGraphTrace   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_trace__pack_to_buffer
                     (const Thread__V1__ThreadGraphTrace   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphTrace *
       thread__v1__thread_graph_trace__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_trace__free_unpacked
                     (Thread__V1__ThreadGraphTrace *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadPartitionResult methods */
void   thread__v1__thread_partition_result__init
                     (Thread__V1__ThreadPartitionResult         *message);
size_t thread__v1__thread_partition_result__get_packed_size
                     (const Thread__V1__ThreadPartitionResult   *message);
size_t thread__v1__thread_partition_result__pack
                     (const Thread__V1__ThreadPartitionResult   *message,
                      uint8_t             *out);
size_t thread__v1__thread_partition_result__pack_to_buffer
                     (const Thread__V1__ThreadPartitionResult   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadPartitionResult *
       thread__v1__thread_partition_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_partition_result__free_unpacked
                     (Thread__V1__ThreadPartitionResult *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadIndexRequest methods */
void   thread__v1__thread_index_request__init
                     (Thread__V1__ThreadIndexRequest         *message);
size_t thread__v1__thread_index_request__get_packed_size
                     (const Thread__V1__ThreadIndexRequest   *message);
size_t thread__v1__thread_index_request__pack
                     (const Thread__V1__ThreadIndexRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_index_request__pack_to_buffer
                     (const Thread__V1__ThreadIndexRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadIndexRequest *
       thread__v1__thread_index_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_index_request__free_unpacked
                     (Thread__V1__ThreadIndexRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadIndexItem methods */
void   thread__v1__thread_index_item__init
                     (Thread__V1__ThreadIndexItem         *message);
size_t thread__v1__thread_index_item__get_packed_size
                     (const Thread__V1__ThreadIndexItem   *message);
size_t thread__v1__thread_index_item__pack
                     (const Thread__V1__ThreadIndexItem   *message,
                      uint8_t             *out);
size_t thread__v1__thread_index_item__pack_to_buffer
                     (const Thread__V1__ThreadIndexItem   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadIndexItem *
       thread__v1__thread_index_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_index_item__free_unpacked
                     (Thread__V1__ThreadIndexItem *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphEntityIn methods */
void   thread__v1__thread_graph_entity_in__init
                     (Thread__V1__ThreadGraphEntityIn         *message);
size_t thread__v1__thread_graph_entity_in__get_packed_size
                     (const Thread__V1__ThreadGraphEntityIn   *message);
size_t thread__v1__thread_graph_entity_in__pack
                     (const Thread__V1__ThreadGraphEntityIn   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_entity_in__pack_to_buffer
                     (const Thread__V1__ThreadGraphEntityIn   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphEntityIn *
       thread__v1__thread_graph_entity_in__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_entity_in__free_unpacked
                     (Thread__V1__ThreadGraphEntityIn *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphRelationIn methods */
void   thread__v1__thread_graph_relation_in__init
                     (Thread__V1__ThreadGraphRelationIn         *message);
size_t thread__v1__thread_graph_relation_in__get_packed_size
                     (const Thread__V1__ThreadGraphRelationIn   *message);
size_t thread__v1__thread_graph_relation_in__pack
                     (const Thread__V1__ThreadGraphRelationIn   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_relation_in__pack_to_buffer
                     (const Thread__V1__ThreadGraphRelationIn   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphRelationIn *
       thread__v1__thread_graph_relation_in__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_relation_in__free_unpacked
                     (Thread__V1__ThreadGraphRelationIn *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadIndexResponse methods */
void   thread__v1__thread_index_response__init
                     (Thread__V1__ThreadIndexResponse         *message);
size_t thread__v1__thread_index_response__get_packed_size
                     (const Thread__V1__ThreadIndexResponse   *message);
size_t thread__v1__thread_index_response__pack
                     (const Thread__V1__ThreadIndexResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_index_response__pack_to_buffer
                     (const Thread__V1__ThreadIndexResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadIndexResponse *
       thread__v1__thread_index_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_index_response__free_unpacked
                     (Thread__V1__ThreadIndexResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadRemoveRequest methods */
void   thread__v1__thread_remove_request__init
                     (Thread__V1__ThreadRemoveRequest         *message);
size_t thread__v1__thread_remove_request__get_packed_size
                     (const Thread__V1__ThreadRemoveRequest   *message);
size_t thread__v1__thread_remove_request__pack
                     (const Thread__V1__ThreadRemoveRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_remove_request__pack_to_buffer
                     (const Thread__V1__ThreadRemoveRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadRemoveRequest *
       thread__v1__thread_remove_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_remove_request__free_unpacked
                     (Thread__V1__ThreadRemoveRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadRemoveResponse methods */
void   thread__v1__thread_remove_response__init
                     (Thread__V1__ThreadRemoveResponse         *message);
size_t thread__v1__thread_remove_response__get_packed_size
                     (const Thread__V1__ThreadRemoveResponse   *message);
size_t thread__v1__thread_remove_response__pack
                     (const Thread__V1__ThreadRemoveResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_remove_response__pack_to_buffer
                     (const Thread__V1__ThreadRemoveResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadRemoveResponse *
       thread__v1__thread_remove_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_remove_response__free_unpacked
                     (Thread__V1__ThreadRemoveResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadUpdateGroupRequest methods */
void   thread__v1__thread_update_group_request__init
                     (Thread__V1__ThreadUpdateGroupRequest         *message);
size_t thread__v1__thread_update_group_request__get_packed_size
                     (const Thread__V1__ThreadUpdateGroupRequest   *message);
size_t thread__v1__thread_update_group_request__pack
                     (const Thread__V1__ThreadUpdateGroupRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_update_group_request__pack_to_buffer
                     (const Thread__V1__ThreadUpdateGroupRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadUpdateGroupRequest *
       thread__v1__thread_update_group_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_update_group_request__free_unpacked
                     (Thread__V1__ThreadUpdateGroupRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadUpdateGroupResponse methods */
void   thread__v1__thread_update_group_response__init
                     (Thread__V1__ThreadUpdateGroupResponse         *message);
size_t thread__v1__thread_update_group_response__get_packed_size
                     (const Thread__V1__ThreadUpdateGroupResponse   *message);
size_t thread__v1__thread_update_group_response__pack
                     (const Thread__V1__ThreadUpdateGroupResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_update_group_response__pack_to_buffer
                     (const Thread__V1__ThreadUpdateGroupResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadUpdateGroupResponse *
       thread__v1__thread_update_group_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_update_group_response__free_unpacked
                     (Thread__V1__ThreadUpdateGroupResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadUpdateDocumentRequest methods */
void   thread__v1__thread_update_document_request__init
                     (Thread__V1__ThreadUpdateDocumentRequest         *message);
size_t thread__v1__thread_update_document_request__get_packed_size
                     (const Thread__V1__ThreadUpdateDocumentRequest   *message);
size_t thread__v1__thread_update_document_request__pack
                     (const Thread__V1__ThreadUpdateDocumentRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_update_document_request__pack_to_buffer
                     (const Thread__V1__ThreadUpdateDocumentRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadUpdateDocumentRequest *
       thread__v1__thread_update_document_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_update_document_request__free_unpacked
                     (Thread__V1__ThreadUpdateDocumentRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadUpdateDocumentResponse methods */
void   thread__v1__thread_update_document_response__init
                     (Thread__V1__ThreadUpdateDocumentResponse         *message);
size_t thread__v1__thread_update_document_response__get_packed_size
                     (const Thread__V1__ThreadUpdateDocumentResponse   *message);
size_t thread__v1__thread_update_document_response__pack
                     (const Thread__V1__ThreadUpdateDocumentResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_update_document_response__pack_to_buffer
                     (const Thread__V1__ThreadUpdateDocumentResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadUpdateDocumentResponse *
       thread__v1__thread_update_document_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_update_document_response__free_unpacked
                     (Thread__V1__ThreadUpdateDocumentResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadStatsRequest methods */
void   thread__v1__thread_stats_request__init
                     (Thread__V1__ThreadStatsRequest         *message);
size_t thread__v1__thread_stats_request__get_packed_size
                     (const Thread__V1__ThreadStatsRequest   *message);
size_t thread__v1__thread_stats_request__pack
                     (const Thread__V1__ThreadStatsRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_stats_request__pack_to_buffer
                     (const Thread__V1__ThreadStatsRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadStatsRequest *
       thread__v1__thread_stats_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_stats_request__free_unpacked
                     (Thread__V1__ThreadStatsRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadStatsResponse methods */
void   thread__v1__thread_stats_response__init
                     (Thread__V1__ThreadStatsResponse         *message);
size_t thread__v1__thread_stats_response__get_packed_size
                     (const Thread__V1__ThreadStatsResponse   *message);
size_t thread__v1__thread_stats_response__pack
                     (const Thread__V1__ThreadStatsResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_stats_response__pack_to_buffer
                     (const Thread__V1__ThreadStatsResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadStatsResponse *
       thread__v1__thread_stats_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_stats_response__free_unpacked
                     (Thread__V1__ThreadStatsResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadDocument methods */
void   thread__v1__thread_document__init
                     (Thread__V1__ThreadDocument         *message);
size_t thread__v1__thread_document__get_packed_size
                     (const Thread__V1__ThreadDocument   *message);
size_t thread__v1__thread_document__pack
                     (const Thread__V1__ThreadDocument   *message,
                      uint8_t             *out);
size_t thread__v1__thread_document__pack_to_buffer
                     (const Thread__V1__ThreadDocument   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadDocument *
       thread__v1__thread_document__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_document__free_unpacked
                     (Thread__V1__ThreadDocument *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGroup methods */
void   thread__v1__thread_group__init
                     (Thread__V1__ThreadGroup         *message);
size_t thread__v1__thread_group__get_packed_size
                     (const Thread__V1__ThreadGroup   *message);
size_t thread__v1__thread_group__pack
                     (const Thread__V1__ThreadGroup   *message,
                      uint8_t             *out);
size_t thread__v1__thread_group__pack_to_buffer
                     (const Thread__V1__ThreadGroup   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGroup *
       thread__v1__thread_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_group__free_unpacked
                     (Thread__V1__ThreadGroup *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadLibraryRequest methods */
void   thread__v1__thread_library_request__init
                     (Thread__V1__ThreadLibraryRequest         *message);
size_t thread__v1__thread_library_request__get_packed_size
                     (const Thread__V1__ThreadLibraryRequest   *message);
size_t thread__v1__thread_library_request__pack
                     (const Thread__V1__ThreadLibraryRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_library_request__pack_to_buffer
                     (const Thread__V1__ThreadLibraryRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadLibraryRequest *
       thread__v1__thread_library_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_library_request__free_unpacked
                     (Thread__V1__ThreadLibraryRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadLibraryResponse methods */
void   thread__v1__thread_library_response__init
                     (Thread__V1__ThreadLibraryResponse         *message);
size_t thread__v1__thread_library_response__get_packed_size
                     (const Thread__V1__ThreadLibraryResponse   *message);
size_t thread__v1__thread_library_response__pack
                     (const Thread__V1__ThreadLibraryResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_library_response__pack_to_buffer
                     (const Thread__V1__ThreadLibraryResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadLibraryResponse *
       thread__v1__thread_library_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_library_response__free_unpacked
                     (Thread__V1__ThreadLibraryResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadDocumentsRequest methods */
void   thread__v1__thread_documents_request__init
                     (Thread__V1__ThreadDocumentsRequest         *message);
size_t thread__v1__thread_documents_request__get_packed_size
                     (const Thread__V1__ThreadDocumentsRequest   *message);
size_t thread__v1__thread_documents_request__pack
                     (const Thread__V1__ThreadDocumentsRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_documents_request__pack_to_buffer
                     (const Thread__V1__ThreadDocumentsRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadDocumentsRequest *
       thread__v1__thread_documents_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_documents_request__free_unpacked
                     (Thread__V1__ThreadDocumentsRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadDocumentContent methods */
void   thread__v1__thread_document_content__init
                     (Thread__V1__ThreadDocumentContent         *message);
size_t thread__v1__thread_document_content__get_packed_size
                     (const Thread__V1__ThreadDocumentContent   *message);
size_t thread__v1__thread_document_content__pack
                     (const Thread__V1__ThreadDocumentContent   *message,
                      uint8_t             *out);
size_t thread__v1__thread_document_content__pack_to_buffer
                     (const Thread__V1__ThreadDocumentContent   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadDocumentContent *
       thread__v1__thread_document_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_document_content__free_unpacked
                     (Thread__V1__ThreadDocumentContent *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadDocumentsResponse methods */
void   thread__v1__thread_documents_response__init
                     (Thread__V1__ThreadDocumentsResponse         *message);
size_t thread__v1__thread_documents_response__get_packed_size
                     (const Thread__V1__ThreadDocumentsResponse   *message);
size_t thread__v1__thread_documents_response__pack
                     (const Thread__V1__ThreadDocumentsResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_documents_response__pack_to_buffer
                     (const Thread__V1__ThreadDocumentsResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadDocumentsResponse *
       thread__v1__thread_documents_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_documents_response__free_unpacked
                     (Thread__V1__ThreadDocumentsResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadExportCorpusRequest methods */
void   thread__v1__thread_export_corpus_request__init
                     (Thread__V1__ThreadExportCorpusRequest         *message);
size_t thread__v1__thread_export_corpus_request__get_packed_size
                     (const Thread__V1__ThreadExportCorpusRequest   *message);
size_t thread__v1__thread_export_corpus_request__pack
                     (const Thread__V1__ThreadExportCorpusRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_export_corpus_request__pack_to_buffer
                     (const Thread__V1__ThreadExportCorpusRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadExportCorpusRequest *
       thread__v1__thread_export_corpus_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_export_corpus_request__free_unpacked
                     (Thread__V1__ThreadExportCorpusRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadExportCorpusResponse methods */
void   thread__v1__thread_export_corpus_response__init
                     (Thread__V1__ThreadExportCorpusResponse         *message);
size_t thread__v1__thread_export_corpus_response__get_packed_size
                     (const Thread__V1__ThreadExportCorpusResponse   *message);
size_t thread__v1__thread_export_corpus_response__pack
                     (const Thread__V1__ThreadExportCorpusResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_export_corpus_response__pack_to_buffer
                     (const Thread__V1__ThreadExportCorpusResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadExportCorpusResponse *
       thread__v1__thread_export_corpus_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_export_corpus_response__free_unpacked
                     (Thread__V1__ThreadExportCorpusResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphQueryRequest methods */
void   thread__v1__thread_graph_query_request__init
                     (Thread__V1__ThreadGraphQueryRequest         *message);
size_t thread__v1__thread_graph_query_request__get_packed_size
                     (const Thread__V1__ThreadGraphQueryRequest   *message);
size_t thread__v1__thread_graph_query_request__pack
                     (const Thread__V1__ThreadGraphQueryRequest   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_query_request__pack_to_buffer
                     (const Thread__V1__ThreadGraphQueryRequest   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphQueryRequest *
       thread__v1__thread_graph_query_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_query_request__free_unpacked
                     (Thread__V1__ThreadGraphQueryRequest *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphEntity methods */
void   thread__v1__thread_graph_entity__init
                     (Thread__V1__ThreadGraphEntity         *message);
size_t thread__v1__thread_graph_entity__get_packed_size
                     (const Thread__V1__ThreadGraphEntity   *message);
size_t thread__v1__thread_graph_entity__pack
                     (const Thread__V1__ThreadGraphEntity   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_entity__pack_to_buffer
                     (const Thread__V1__ThreadGraphEntity   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphEntity *
       thread__v1__thread_graph_entity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_entity__free_unpacked
                     (Thread__V1__ThreadGraphEntity *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphRelationship methods */
void   thread__v1__thread_graph_relationship__init
                     (Thread__V1__ThreadGraphRelationship         *message);
size_t thread__v1__thread_graph_relationship__get_packed_size
                     (const Thread__V1__ThreadGraphRelationship   *message);
size_t thread__v1__thread_graph_relationship__pack
                     (const Thread__V1__ThreadGraphRelationship   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_relationship__pack_to_buffer
                     (const Thread__V1__ThreadGraphRelationship   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphRelationship *
       thread__v1__thread_graph_relationship__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_relationship__free_unpacked
                     (Thread__V1__ThreadGraphRelationship *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphDocument methods */
void   thread__v1__thread_graph_document__init
                     (Thread__V1__ThreadGraphDocument         *message);
size_t thread__v1__thread_graph_document__get_packed_size
                     (const Thread__V1__ThreadGraphDocument   *message);
size_t thread__v1__thread_graph_document__pack
                     (const Thread__V1__ThreadGraphDocument   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_document__pack_to_buffer
                     (const Thread__V1__ThreadGraphDocument   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphDocument *
       thread__v1__thread_graph_document__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_document__free_unpacked
                     (Thread__V1__ThreadGraphDocument *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphStats methods */
void   thread__v1__thread_graph_stats__init
                     (Thread__V1__ThreadGraphStats         *message);
size_t thread__v1__thread_graph_stats__get_packed_size
                     (const Thread__V1__ThreadGraphStats   *message);
size_t thread__v1__thread_graph_stats__pack
                     (const Thread__V1__ThreadGraphStats   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_stats__pack_to_buffer
                     (const Thread__V1__ThreadGraphStats   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphStats *
       thread__v1__thread_graph_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_stats__free_unpacked
                     (Thread__V1__ThreadGraphStats *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadGraphQueryResponse methods */
void   thread__v1__thread_graph_query_response__init
                     (Thread__V1__ThreadGraphQueryResponse         *message);
size_t thread__v1__thread_graph_query_response__get_packed_size
                     (const Thread__V1__ThreadGraphQueryResponse   *message);
size_t thread__v1__thread_graph_query_response__pack
                     (const Thread__V1__ThreadGraphQueryResponse   *message,
                      uint8_t             *out);
size_t thread__v1__thread_graph_query_response__pack_to_buffer
                     (const Thread__V1__ThreadGraphQueryResponse   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadGraphQueryResponse *
       thread__v1__thread_graph_query_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_graph_query_response__free_unpacked
                     (Thread__V1__ThreadGraphQueryResponse *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadSessionMessage methods */
void   thread__v1__thread_session_message__init
                     (Thread__V1__ThreadSessionMessage         *message);
size_t thread__v1__thread_session_message__get_packed_size
                     (const Thread__V1__ThreadSessionMessage   *message);
size_t thread__v1__thread_session_message__pack
                     (const Thread__V1__ThreadSessionMessage   *message,
                      uint8_t             *out);
size_t thread__v1__thread_session_message__pack_to_buffer
                     (const Thread__V1__ThreadSessionMessage   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadSessionMessage *
       thread__v1__thread_session_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_session_message__free_unpacked
                     (Thread__V1__ThreadSessionMessage *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadSessionPing methods */
void   thread__v1__thread_session_ping__init
                     (Thread__V1__ThreadSessionPing         *message);
size_t thread__v1__thread_session_ping__get_packed_size
                     (const Thread__V1__ThreadSessionPing   *message);
size_t thread__v1__thread_session_ping__pack
                     (const Thread__V1__ThreadSessionPing   *message,
                      uint8_t             *out);
size_t thread__v1__thread_session_ping__pack_to_buffer
                     (const Thread__V1__ThreadSessionPing   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadSessionPing *
       thread__v1__thread_session_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_session_ping__free_unpacked
                     (Thread__V1__ThreadSessionPing *message,
                      ProtobufCAllocator *allocator);
/* Thread__V1__ThreadSessionPong methods */
void   thread__v1__thread_session_pong__init
                     (Thread__V1__ThreadSessionPong         *message);
size_t thread__v1__thread_session_pong__get_packed_size
                     (const Thread__V1__ThreadSessionPong   *message);
size_t thread__v1__thread_session_pong__pack
                     (const Thread__V1__ThreadSessionPong   *message,
                      uint8_t             *out);
size_t thread__v1__thread_session_pong__pack_to_buffer
                     (const Thread__V1__ThreadSessionPong   *message,
                      ProtobufCBuffer     *buffer);
Thread__V1__ThreadSessionPong *
       thread__v1__thread_session_pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread__v1__thread_session_pong__free_unpacked
                     (Thread__V1__ThreadSessionPong *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Thread__V1__RegisterRequest_Closure)
                 (const Thread__V1__RegisterRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__RegisterResponse_Closure)
                 (const Thread__V1__RegisterResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__HeartbeatRequest_Closure)
                 (const Thread__V1__HeartbeatRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__HeartbeatResponse_Closure)
                 (const Thread__V1__HeartbeatResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__AvailabilityUpdateRequest_Closure)
                 (const Thread__V1__AvailabilityUpdateRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__AvailabilityUpdateResponse_Closure)
                 (const Thread__V1__AvailabilityUpdateResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadSearchRequest_Closure)
                 (const Thread__V1__ThreadSearchRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadSearchResponse_Closure)
                 (const Thread__V1__ThreadSearchResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphTrace_Closure)
                 (const Thread__V1__ThreadGraphTrace *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadPartitionResult_Closure)
                 (const Thread__V1__ThreadPartitionResult *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadIndexRequest_Closure)
                 (const Thread__V1__ThreadIndexRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadIndexItem_Closure)
                 (const Thread__V1__ThreadIndexItem *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphEntityIn_Closure)
                 (const Thread__V1__ThreadGraphEntityIn *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphRelationIn_Closure)
                 (const Thread__V1__ThreadGraphRelationIn *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadIndexResponse_Closure)
                 (const Thread__V1__ThreadIndexResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadRemoveRequest_Closure)
                 (const Thread__V1__ThreadRemoveRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadRemoveResponse_Closure)
                 (const Thread__V1__ThreadRemoveResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadUpdateGroupRequest_Closure)
                 (const Thread__V1__ThreadUpdateGroupRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadUpdateGroupResponse_Closure)
                 (const Thread__V1__ThreadUpdateGroupResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadUpdateDocumentRequest_Closure)
                 (const Thread__V1__ThreadUpdateDocumentRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadUpdateDocumentResponse_Closure)
                 (const Thread__V1__ThreadUpdateDocumentResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadStatsRequest_Closure)
                 (const Thread__V1__ThreadStatsRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadStatsResponse_Closure)
                 (const Thread__V1__ThreadStatsResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadDocument_Closure)
                 (const Thread__V1__ThreadDocument *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGroup_Closure)
                 (const Thread__V1__ThreadGroup *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadLibraryRequest_Closure)
                 (const Thread__V1__ThreadLibraryRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadLibraryResponse_Closure)
                 (const Thread__V1__ThreadLibraryResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadDocumentsRequest_Closure)
                 (const Thread__V1__ThreadDocumentsRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadDocumentContent_Closure)
                 (const Thread__V1__ThreadDocumentContent *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadDocumentsResponse_Closure)
                 (const Thread__V1__ThreadDocumentsResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadExportCorpusRequest_Closure)
                 (const Thread__V1__ThreadExportCorpusRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadExportCorpusResponse_Closure)
                 (const Thread__V1__ThreadExportCorpusResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphQueryRequest_Closure)
                 (const Thread__V1__ThreadGraphQueryRequest *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphEntity_Closure)
                 (const Thread__V1__ThreadGraphEntity *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphRelationship_Closure)
                 (const Thread__V1__ThreadGraphRelationship *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphDocument_Closure)
                 (const Thread__V1__ThreadGraphDocument *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphStats_Closure)
                 (const Thread__V1__ThreadGraphStats *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadGraphQueryResponse_Closure)
                 (const Thread__V1__ThreadGraphQueryResponse *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadSessionMessage_Closure)
                 (const Thread__V1__ThreadSessionMessage *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadSessionPing_Closure)
                 (const Thread__V1__ThreadSessionPing *message,
                  void *closure_data);
typedef void (*Thread__V1__ThreadSessionPong_Closure)
                 (const Thread__V1__ThreadSessionPong *message,
                  void *closure_data);

/* --- services --- */

typedef struct Thread__V1__ThreadRegistration_Service Thread__V1__ThreadRegistration_Service;
struct Thread__V1__ThreadRegistration_Service
{
  ProtobufCService base;
  void (*register_)(Thread__V1__ThreadRegistration_Service *service,
                   const Thread__V1__RegisterRequest *input,
                   Thread__V1__RegisterResponse_Closure closure,
                   void *closure_data);
  void (*heartbeat)(Thread__V1__ThreadRegistration_Service *service,
                    const Thread__V1__HeartbeatRequest *input,
                    Thread__V1__HeartbeatResponse_Closure closure,
                    void *closure_data);
  void (*update_availability)(Thread__V1__ThreadRegistration_Service *service,
                              const Thread__V1__AvailabilityUpdateRequest *input,
                              Thread__V1__AvailabilityUpdateResponse_Closure closure,
                              void *closure_data);
  void (*session)(Thread__V1__ThreadRegistration_Service *service,
                  const Thread__V1__ThreadSessionMessage *input,
                  Thread__V1__ThreadSessionMessage_Closure closure,
                  void *closure_data);
};
typedef void (*Thread__V1__ThreadRegistration_ServiceDestroy)(Thread__V1__ThreadRegistration_Service *);
void thread__v1__thread_registration__init (Thread__V1__ThreadRegistration_Service *service,
                                            Thread__V1__ThreadRegistration_ServiceDestroy destroy);
#define THREAD__V1__THREAD_REGISTRATION__BASE_INIT \
    { &thread__v1__thread_registration__descriptor, protobuf_c_service_invoke_internal, NULL }
#define THREAD__V1__THREAD_REGISTRATION__INIT(function_prefix__) \
    { THREAD__V1__THREAD_REGISTRATION__BASE_INIT,\
      function_prefix__ ## register_,\
      function_prefix__ ## heartbeat,\
      function_prefix__ ## update_availability,\
      function_prefix__ ## session  }
void thread__v1__thread_registration__register(ProtobufCService *service,
                                               const Thread__V1__RegisterRequest *input,
                                               Thread__V1__RegisterResponse_Closure closure,
                                               void *closure_data);
void thread__v1__thread_registration__heartbeat(ProtobufCService *service,
                                                const Thread__V1__HeartbeatRequest *input,
                                                Thread__V1__HeartbeatResponse_Closure closure,
                                                void *closure_data);
void thread__v1__thread_registration__update_availability(ProtobufCService *service,
                                                          const Thread__V1__AvailabilityUpdateRequest *input,
                                                          Thread__V1__AvailabilityUpdateResponse_Closure closure,
                                                          void *closure_data);
void thread__v1__thread_registration__session(ProtobufCService *service,
                                              const Thread__V1__ThreadSessionMessage *input,
                                              Thread__V1__ThreadSessionMessage_Closure closure,
                                              void *closure_data);
typedef struct Thread__V1__ThreadQuery_Service Thread__V1__ThreadQuery_Service;
struct Thread__V1__ThreadQuery_Service
{
  ProtobufCService base;
  void (*search)(Thread__V1__ThreadQuery_Service *service,
                 const Thread__V1__ThreadSearchRequest *input,
                 Thread__V1__ThreadSearchResponse_Closure closure,
                 void *closure_data);
  void (*index)(Thread__V1__ThreadQuery_Service *service,
                const Thread__V1__ThreadIndexRequest *input,
                Thread__V1__ThreadIndexResponse_Closure closure,
                void *closure_data);
  void (*remove)(Thread__V1__ThreadQuery_Service *service,
                 const Thread__V1__ThreadRemoveRequest *input,
                 Thread__V1__ThreadRemoveResponse_Closure closure,
                 void *closure_data);
};
typedef void (*Thread__V1__ThreadQuery_ServiceDestroy)(Thread__V1__ThreadQuery_Service *);
void thread__v1__thread_query__init (Thread__V1__ThreadQuery_Service *service,
                                     Thread__V1__ThreadQuery_ServiceDestroy destroy);
#define THREAD__V1__THREAD_QUERY__BASE_INIT \
    { &thread__v1__thread_query__descriptor, protobuf_c_service_invoke_internal, NULL }
#define THREAD__V1__THREAD_QUERY__INIT(function_prefix__) \
    { THREAD__V1__THREAD_QUERY__BASE_INIT,\
      function_prefix__ ## search,\
      function_prefix__ ## index,\
      function_prefix__ ## remove  }
void thread__v1__thread_query__search(ProtobufCService *service,
                                      const Thread__V1__ThreadSearchRequest *input,
                                      Thread__V1__ThreadSearchResponse_Closure closure,
                                      void *closure_data);
void thread__v1__thread_query__index(ProtobufCService *service,
                                     const Thread__V1__ThreadIndexRequest *input,
                                     Thread__V1__ThreadIndexResponse_Closure closure,
                                     void *closure_data);
void thread__v1__thread_query__remove(ProtobufCService *service,
                                      const Thread__V1__ThreadRemoveRequest *input,
                                      Thread__V1__ThreadRemoveResponse_Closure closure,
                                      void *closure_data);
typedef struct Thread__V1__ThreadUpdate_Service Thread__V1__ThreadUpdate_Service;
struct Thread__V1__ThreadUpdate_Service
{
  ProtobufCService base;
  void (*update_group)(Thread__V1__ThreadUpdate_Service *service,
                       const Thread__V1__ThreadUpdateGroupRequest *input,
                       Thread__V1__ThreadUpdateGroupResponse_Closure closure,
                       void *closure_data);
  void (*update_document)(Thread__V1__ThreadUpdate_Service *service,
                          const Thread__V1__ThreadUpdateDocumentRequest *input,
                          Thread__V1__ThreadUpdateDocumentResponse_Closure closure,
                          void *closure_data);
  void (*stats)(Thread__V1__ThreadUpdate_Service *service,
                const Thread__V1__ThreadStatsRequest *input,
                Thread__V1__ThreadStatsResponse_Closure closure,
                void *closure_data);
};
typedef void (*Thread__V1__ThreadUpdate_ServiceDestroy)(Thread__V1__ThreadUpdate_Service *);
void thread__v1__thread_update__init (Thread__V1__ThreadUpdate_Service *service,
                                      Thread__V1__ThreadUpdate_ServiceDestroy destroy);
#define THREAD__V1__THREAD_UPDATE__BASE_INIT \
    { &thread__v1__thread_update__descriptor, protobuf_c_service_invoke_internal, NULL }
#define THREAD__V1__THREAD_UPDATE__INIT(function_prefix__) \
    { THREAD__V1__THREAD_UPDATE__BASE_INIT,\
      function_prefix__ ## update_group,\
      function_prefix__ ## update_document,\
      function_prefix__ ## stats  }
void thread__v1__thread_update__update_group(ProtobufCService *service,
                                             const Thread__V1__ThreadUpdateGroupRequest *input,
                                             Thread__V1__ThreadUpdateGroupResponse_Closure closure,
                                             void *closure_data);
void thread__v1__thread_update__update_document(ProtobufCService *service,
                                                const Thread__V1__ThreadUpdateDocumentRequest *input,
                                                Thread__V1__ThreadUpdateDocumentResponse_Closure closure,
                                                void *closure_data);
void thread__v1__thread_update__stats(ProtobufCService *service,
                                      const Thread__V1__ThreadStatsRequest *input,
                                      Thread__V1__ThreadStatsResponse_Closure closure,
                                      void *closure_data);
typedef struct Thread__V1__ThreadLibrary_Service Thread__V1__ThreadLibrary_Service;
struct Thread__V1__ThreadLibrary_Service
{
  ProtobufCService base;
  void (*library)(Thread__V1__ThreadLibrary_Service *service,
                  const Thread__V1__ThreadLibraryRequest *input,
                  Thread__V1__ThreadLibraryResponse_Closure closure,
                  void *closure_data);
  void (*documents)(Thread__V1__ThreadLibrary_Service *service,
                    const Thread__V1__ThreadDocumentsRequest *input,
                    Thread__V1__ThreadDocumentsResponse_Closure closure,
                    void *closure_data);
  void (*export_corpus)(Thread__V1__ThreadLibrary_Service *service,
                        const Thread__V1__ThreadExportCorpusRequest *input,
                        Thread__V1__ThreadExportCorpusResponse_Closure closure,
                        void *closure_data);
};
typedef void (*Thread__V1__ThreadLibrary_ServiceDestroy)(Thread__V1__ThreadLibrary_Service *);
void thread__v1__thread_library__init (Thread__V1__ThreadLibrary_Service *service,
                                       Thread__V1__ThreadLibrary_ServiceDestroy destroy);
#define THREAD__V1__THREAD_LIBRARY__BASE_INIT \
    { &thread__v1__thread_library__descriptor, protobuf_c_service_invoke_internal, NULL }
#define THREAD__V1__THREAD_LIBRARY__INIT(function_prefix__) \
    { THREAD__V1__THREAD_LIBRARY__BASE_INIT,\
      function_prefix__ ## library,\
      function_prefix__ ## documents,\
      function_prefix__ ## export_corpus  }
void thread__v1__thread_library__library(ProtobufCService *service,
                                         const Thread__V1__ThreadLibraryRequest *input,
                                         Thread__V1__ThreadLibraryResponse_Closure closure,
                                         void *closure_data);
void thread__v1__thread_library__documents(ProtobufCService *service,
                                           const Thread__V1__ThreadDocumentsRequest *input,
                                           Thread__V1__ThreadDocumentsResponse_Closure closure,
                                           void *closure_data);
void thread__v1__thread_library__export_corpus(ProtobufCService *service,
                                               const Thread__V1__ThreadExportCorpusRequest *input,
                                               Thread__V1__ThreadExportCorpusResponse_Closure closure,
                                               void *closure_data);
typedef struct Thread__V1__ThreadGraph_Service Thread__V1__ThreadGraph_Service;
struct Thread__V1__ThreadGraph_Service
{
  ProtobufCService base;
  void (*query)(Thread__V1__ThreadGraph_Service *service,
                const Thread__V1__ThreadGraphQueryRequest *input,
                Thread__V1__ThreadGraphQueryResponse_Closure closure,
                void *closure_data);
};
typedef void (*Thread__V1__ThreadGraph_ServiceDestroy)(Thread__V1__ThreadGraph_Service *);
void thread__v1__thread_graph__init (Thread__V1__ThreadGraph_Service *service,
                                     Thread__V1__ThreadGraph_ServiceDestroy destroy);
#define THREAD__V1__THREAD_GRAPH__BASE_INIT \
    { &thread__v1__thread_graph__descriptor, protobuf_c_service_invoke_internal, NULL }
#define THREAD__V1__THREAD_GRAPH__INIT(function_prefix__) \
    { THREAD__V1__THREAD_GRAPH__BASE_INIT,\
      function_prefix__ ## query  }
void thread__v1__thread_graph__query(ProtobufCService *service,
                                     const Thread__V1__ThreadGraphQueryRequest *input,
                                     Thread__V1__ThreadGraphQueryResponse_Closure closure,
                                     void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor thread__v1__register_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__register_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__heartbeat_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__heartbeat_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__availability_update_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__availability_update_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_search_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_search_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_trace__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_partition_result__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_index_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_index_item__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_entity_in__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_relation_in__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_index_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_remove_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_remove_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_update_group_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_update_group_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_update_document_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_update_document_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_stats_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_stats_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_document__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_group__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_library_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_library_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_documents_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_document_content__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_documents_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_export_corpus_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_export_corpus_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_query_request__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_entity__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_relationship__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_document__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_stats__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_graph_query_response__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_session_message__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_session_ping__descriptor;
extern const ProtobufCMessageDescriptor thread__v1__thread_session_pong__descriptor;
extern const ProtobufCServiceDescriptor thread__v1__thread_registration__descriptor;
extern const ProtobufCServiceDescriptor thread__v1__thread_query__descriptor;
extern const ProtobufCServiceDescriptor thread__v1__thread_update__descriptor;
extern const ProtobufCServiceDescriptor thread__v1__thread_library__descriptor;
extern const ProtobufCServiceDescriptor thread__v1__thread_graph__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_thread_2eproto__INCLUDED */
