/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fleet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "conduit/fleet.pb-c.h"
void   fleet__v1__list_adapters_request__init
                     (Fleet__V1__ListAdaptersRequest         *message)
{
  static const Fleet__V1__ListAdaptersRequest init_value = FLEET__V1__LIST_ADAPTERS_REQUEST__INIT;
  *message = init_value;
}
size_t fleet__v1__list_adapters_request__get_packed_size
                     (const Fleet__V1__ListAdaptersRequest *message)
{
  assert(message->base.descriptor == &fleet__v1__list_adapters_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__list_adapters_request__pack
                     (const Fleet__V1__ListAdaptersRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__list_adapters_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__list_adapters_request__pack_to_buffer
                     (const Fleet__V1__ListAdaptersRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__list_adapters_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__ListAdaptersRequest *
       fleet__v1__list_adapters_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__ListAdaptersRequest *)
     protobuf_c_message_unpack (&fleet__v1__list_adapters_request__descriptor,
                                allocator, len, data);
}
void   fleet__v1__list_adapters_request__free_unpacked
                     (Fleet__V1__ListAdaptersRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__list_adapters_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fleet__v1__list_adapters_response__init
                     (Fleet__V1__ListAdaptersResponse         *message)
{
  static const Fleet__V1__ListAdaptersResponse init_value = FLEET__V1__LIST_ADAPTERS_RESPONSE__INIT;
  *message = init_value;
}
size_t fleet__v1__list_adapters_response__get_packed_size
                     (const Fleet__V1__ListAdaptersResponse *message)
{
  assert(message->base.descriptor == &fleet__v1__list_adapters_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__list_adapters_response__pack
                     (const Fleet__V1__ListAdaptersResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__list_adapters_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__list_adapters_response__pack_to_buffer
                     (const Fleet__V1__ListAdaptersResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__list_adapters_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__ListAdaptersResponse *
       fleet__v1__list_adapters_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__ListAdaptersResponse *)
     protobuf_c_message_unpack (&fleet__v1__list_adapters_response__descriptor,
                                allocator, len, data);
}
void   fleet__v1__list_adapters_response__free_unpacked
                     (Fleet__V1__ListAdaptersResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__list_adapters_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fleet__v1__adapter_status_request__init
                     (Fleet__V1__AdapterStatusRequest         *message)
{
  static const Fleet__V1__AdapterStatusRequest init_value = FLEET__V1__ADAPTER_STATUS_REQUEST__INIT;
  *message = init_value;
}
size_t fleet__v1__adapter_status_request__get_packed_size
                     (const Fleet__V1__AdapterStatusRequest *message)
{
  assert(message->base.descriptor == &fleet__v1__adapter_status_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__adapter_status_request__pack
                     (const Fleet__V1__AdapterStatusRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__adapter_status_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__adapter_status_request__pack_to_buffer
                     (const Fleet__V1__AdapterStatusRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__adapter_status_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__AdapterStatusRequest *
       fleet__v1__adapter_status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__AdapterStatusRequest *)
     protobuf_c_message_unpack (&fleet__v1__adapter_status_request__descriptor,
                                allocator, len, data);
}
void   fleet__v1__adapter_status_request__free_unpacked
                     (Fleet__V1__AdapterStatusRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__adapter_status_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fleet__v1__lo_raslot__init
                     (Fleet__V1__LoRASlot         *message)
{
  static const Fleet__V1__LoRASlot init_value = FLEET__V1__LO_RASLOT__INIT;
  *message = init_value;
}
size_t fleet__v1__lo_raslot__get_packed_size
                     (const Fleet__V1__LoRASlot *message)
{
  assert(message->base.descriptor == &fleet__v1__lo_raslot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__lo_raslot__pack
                     (const Fleet__V1__LoRASlot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__lo_raslot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__lo_raslot__pack_to_buffer
                     (const Fleet__V1__LoRASlot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__lo_raslot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__LoRASlot *
       fleet__v1__lo_raslot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__LoRASlot *)
     protobuf_c_message_unpack (&fleet__v1__lo_raslot__descriptor,
                                allocator, len, data);
}
void   fleet__v1__lo_raslot__free_unpacked
                     (Fleet__V1__LoRASlot *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__lo_raslot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fleet__v1__training_pair__init
                     (Fleet__V1__TrainingPair         *message)
{
  static const Fleet__V1__TrainingPair init_value = FLEET__V1__TRAINING_PAIR__INIT;
  *message = init_value;
}
size_t fleet__v1__training_pair__get_packed_size
                     (const Fleet__V1__TrainingPair *message)
{
  assert(message->base.descriptor == &fleet__v1__training_pair__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__training_pair__pack
                     (const Fleet__V1__TrainingPair *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__training_pair__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__training_pair__pack_to_buffer
                     (const Fleet__V1__TrainingPair *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__training_pair__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__TrainingPair *
       fleet__v1__training_pair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__TrainingPair *)
     protobuf_c_message_unpack (&fleet__v1__training_pair__descriptor,
                                allocator, len, data);
}
void   fleet__v1__training_pair__free_unpacked
                     (Fleet__V1__TrainingPair *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__training_pair__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fleet__v1__train_request__init
                     (Fleet__V1__TrainRequest         *message)
{
  static const Fleet__V1__TrainRequest init_value = FLEET__V1__TRAIN_REQUEST__INIT;
  *message = init_value;
}
size_t fleet__v1__train_request__get_packed_size
                     (const Fleet__V1__TrainRequest *message)
{
  assert(message->base.descriptor == &fleet__v1__train_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__train_request__pack
                     (const Fleet__V1__TrainRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__train_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__train_request__pack_to_buffer
                     (const Fleet__V1__TrainRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__train_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__TrainRequest *
       fleet__v1__train_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__TrainRequest *)
     protobuf_c_message_unpack (&fleet__v1__train_request__descriptor,
                                allocator, len, data);
}
void   fleet__v1__train_request__free_unpacked
                     (Fleet__V1__TrainRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__train_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fleet__v1__train_progress__init
                     (Fleet__V1__TrainProgress         *message)
{
  static const Fleet__V1__TrainProgress init_value = FLEET__V1__TRAIN_PROGRESS__INIT;
  *message = init_value;
}
size_t fleet__v1__train_progress__get_packed_size
                     (const Fleet__V1__TrainProgress *message)
{
  assert(message->base.descriptor == &fleet__v1__train_progress__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__train_progress__pack
                     (const Fleet__V1__TrainProgress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__train_progress__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__train_progress__pack_to_buffer
                     (const Fleet__V1__TrainProgress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__train_progress__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__TrainProgress *
       fleet__v1__train_progress__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__TrainProgress *)
     protobuf_c_message_unpack (&fleet__v1__train_progress__descriptor,
                                allocator, len, data);
}
void   fleet__v1__train_progress__free_unpacked
                     (Fleet__V1__TrainProgress *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__train_progress__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fleet__v1__complete_request__init
                     (Fleet__V1__CompleteRequest         *message)
{
  static const Fleet__V1__CompleteRequest init_value = FLEET__V1__COMPLETE_REQUEST__INIT;
  *message = init_value;
}
size_t fleet__v1__complete_request__get_packed_size
                     (const Fleet__V1__CompleteRequest *message)
{
  assert(message->base.descriptor == &fleet__v1__complete_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__complete_request__pack
                     (const Fleet__V1__CompleteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__complete_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__complete_request__pack_to_buffer
                     (const Fleet__V1__CompleteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__complete_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__CompleteRequest *
       fleet__v1__complete_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__CompleteRequest *)
     protobuf_c_message_unpack (&fleet__v1__complete_request__descriptor,
                                allocator, len, data);
}
void   fleet__v1__complete_request__free_unpacked
                     (Fleet__V1__CompleteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__complete_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fleet__v1__complete_response__init
                     (Fleet__V1__CompleteResponse         *message)
{
  static const Fleet__V1__CompleteResponse init_value = FLEET__V1__COMPLETE_RESPONSE__INIT;
  *message = init_value;
}
size_t fleet__v1__complete_response__get_packed_size
                     (const Fleet__V1__CompleteResponse *message)
{
  assert(message->base.descriptor == &fleet__v1__complete_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fleet__v1__complete_response__pack
                     (const Fleet__V1__CompleteResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fleet__v1__complete_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fleet__v1__complete_response__pack_to_buffer
                     (const Fleet__V1__CompleteResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fleet__v1__complete_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fleet__V1__CompleteResponse *
       fleet__v1__complete_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fleet__V1__CompleteResponse *)
     protobuf_c_message_unpack (&fleet__v1__complete_response__descriptor,
                                allocator, len, data);
}
void   fleet__v1__complete_response__free_unpacked
                     (Fleet__V1__CompleteResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fleet__v1__complete_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor fleet__v1__list_adapters_request__field_descriptors[1] =
{
  {
    "thread_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__ListAdaptersRequest, thread_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__list_adapters_request__field_indices_by_name[] = {
  0,   /* field[0] = thread_id */
};
static const ProtobufCIntRange fleet__v1__list_adapters_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fleet__v1__list_adapters_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.ListAdaptersRequest",
  "ListAdaptersRequest",
  "Fleet__V1__ListAdaptersRequest",
  "fleet.v1",
  sizeof(Fleet__V1__ListAdaptersRequest),
  1,
  fleet__v1__list_adapters_request__field_descriptors,
  fleet__v1__list_adapters_request__field_indices_by_name,
  1,  fleet__v1__list_adapters_request__number_ranges,
  (ProtobufCMessageInit) fleet__v1__list_adapters_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fleet__v1__list_adapters_response__field_descriptors[1] =
{
  {
    "slots",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fleet__V1__ListAdaptersResponse, n_slots),
    offsetof(Fleet__V1__ListAdaptersResponse, slots),
    &fleet__v1__lo_raslot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__list_adapters_response__field_indices_by_name[] = {
  0,   /* field[0] = slots */
};
static const ProtobufCIntRange fleet__v1__list_adapters_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fleet__v1__list_adapters_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.ListAdaptersResponse",
  "ListAdaptersResponse",
  "Fleet__V1__ListAdaptersResponse",
  "fleet.v1",
  sizeof(Fleet__V1__ListAdaptersResponse),
  1,
  fleet__v1__list_adapters_response__field_descriptors,
  fleet__v1__list_adapters_response__field_indices_by_name,
  1,  fleet__v1__list_adapters_response__number_ranges,
  (ProtobufCMessageInit) fleet__v1__list_adapters_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fleet__v1__adapter_status_request__field_descriptors[2] =
{
  {
    "thread_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__AdapterStatusRequest, thread_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ability_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__AdapterStatusRequest, ability_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__adapter_status_request__field_indices_by_name[] = {
  1,   /* field[1] = ability_id */
  0,   /* field[0] = thread_id */
};
static const ProtobufCIntRange fleet__v1__adapter_status_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fleet__v1__adapter_status_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.AdapterStatusRequest",
  "AdapterStatusRequest",
  "Fleet__V1__AdapterStatusRequest",
  "fleet.v1",
  sizeof(Fleet__V1__AdapterStatusRequest),
  2,
  fleet__v1__adapter_status_request__field_descriptors,
  fleet__v1__adapter_status_request__field_indices_by_name,
  1,  fleet__v1__adapter_status_request__number_ranges,
  (ProtobufCMessageInit) fleet__v1__adapter_status_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fleet__v1__lo_raslot__field_descriptors[10] =
{
  {
    "ability_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, ability_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "generation",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, generation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pair_count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, pair_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trained_at_unix",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, trained_at_unix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ready",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, ready),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "artifact_path",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, artifact_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cid",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, cid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model_id",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, model_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schema_json",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, schema_json),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "training",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__LoRASlot, training),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__lo_raslot__field_indices_by_name[] = {
  0,   /* field[0] = ability_id */
  5,   /* field[5] = artifact_path */
  6,   /* field[6] = cid */
  1,   /* field[1] = generation */
  7,   /* field[7] = model_id */
  2,   /* field[2] = pair_count */
  4,   /* field[4] = ready */
  8,   /* field[8] = schema_json */
  3,   /* field[3] = trained_at_unix */
  9,   /* field[9] = training */
};
static const ProtobufCIntRange fleet__v1__lo_raslot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor fleet__v1__lo_raslot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.LoRASlot",
  "LoRASlot",
  "Fleet__V1__LoRASlot",
  "fleet.v1",
  sizeof(Fleet__V1__LoRASlot),
  10,
  fleet__v1__lo_raslot__field_descriptors,
  fleet__v1__lo_raslot__field_indices_by_name,
  1,  fleet__v1__lo_raslot__number_ranges,
  (ProtobufCMessageInit) fleet__v1__lo_raslot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fleet__v1__training_pair__field_descriptors[2] =
{
  {
    "input_json",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainingPair, input_json),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_json",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainingPair, output_json),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__training_pair__field_indices_by_name[] = {
  0,   /* field[0] = input_json */
  1,   /* field[1] = output_json */
};
static const ProtobufCIntRange fleet__v1__training_pair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fleet__v1__training_pair__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.TrainingPair",
  "TrainingPair",
  "Fleet__V1__TrainingPair",
  "fleet.v1",
  sizeof(Fleet__V1__TrainingPair),
  2,
  fleet__v1__training_pair__field_descriptors,
  fleet__v1__training_pair__field_indices_by_name,
  1,  fleet__v1__training_pair__number_ranges,
  (ProtobufCMessageInit) fleet__v1__training_pair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fleet__v1__train_request__field_descriptors[7] =
{
  {
    "thread_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainRequest, thread_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ability_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainRequest, ability_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainRequest, model_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pairs",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fleet__V1__TrainRequest, n_pairs),
    offsetof(Fleet__V1__TrainRequest, pairs),
    &fleet__v1__training_pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainRequest, owner_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_ids",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Fleet__V1__TrainRequest, n_group_ids),
    offsetof(Fleet__V1__TrainRequest, group_ids),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "document_id_prefix",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainRequest, document_id_prefix),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__train_request__field_indices_by_name[] = {
  1,   /* field[1] = ability_id */
  6,   /* field[6] = document_id_prefix */
  5,   /* field[5] = group_ids */
  2,   /* field[2] = model_id */
  4,   /* field[4] = owner_id */
  3,   /* field[3] = pairs */
  0,   /* field[0] = thread_id */
};
static const ProtobufCIntRange fleet__v1__train_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor fleet__v1__train_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.TrainRequest",
  "TrainRequest",
  "Fleet__V1__TrainRequest",
  "fleet.v1",
  sizeof(Fleet__V1__TrainRequest),
  7,
  fleet__v1__train_request__field_descriptors,
  fleet__v1__train_request__field_indices_by_name,
  1,  fleet__v1__train_request__number_ranges,
  (ProtobufCMessageInit) fleet__v1__train_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fleet__v1__train_progress__field_descriptors[5] =
{
  {
    "stage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainProgress, stage),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iteration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainProgress, iteration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loss",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainProgress, loss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainProgress, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__TrainProgress, slot),
    &fleet__v1__lo_raslot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__train_progress__field_indices_by_name[] = {
  1,   /* field[1] = iteration */
  2,   /* field[2] = loss */
  3,   /* field[3] = message */
  4,   /* field[4] = slot */
  0,   /* field[0] = stage */
};
static const ProtobufCIntRange fleet__v1__train_progress__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor fleet__v1__train_progress__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.TrainProgress",
  "TrainProgress",
  "Fleet__V1__TrainProgress",
  "fleet.v1",
  sizeof(Fleet__V1__TrainProgress),
  5,
  fleet__v1__train_progress__field_descriptors,
  fleet__v1__train_progress__field_indices_by_name,
  1,  fleet__v1__train_progress__number_ranges,
  (ProtobufCMessageInit) fleet__v1__train_progress__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fleet__v1__complete_request__field_descriptors[4] =
{
  {
    "thread_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteRequest, thread_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ability_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteRequest, ability_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteRequest, cid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_json",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteRequest, input_json),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__complete_request__field_indices_by_name[] = {
  1,   /* field[1] = ability_id */
  2,   /* field[2] = cid */
  3,   /* field[3] = input_json */
  0,   /* field[0] = thread_id */
};
static const ProtobufCIntRange fleet__v1__complete_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor fleet__v1__complete_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.CompleteRequest",
  "CompleteRequest",
  "Fleet__V1__CompleteRequest",
  "fleet.v1",
  sizeof(Fleet__V1__CompleteRequest),
  4,
  fleet__v1__complete_request__field_descriptors,
  fleet__v1__complete_request__field_indices_by_name,
  1,  fleet__v1__complete_request__number_ranges,
  (ProtobufCMessageInit) fleet__v1__complete_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fleet__v1__complete_response__field_descriptors[5] =
{
  {
    "output_json",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteResponse, output_json),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raw_text",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteResponse, raw_text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forced_fraction",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteResponse, forced_fraction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prompt_tokens",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteResponse, prompt_tokens),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fleet__V1__CompleteResponse, cid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fleet__v1__complete_response__field_indices_by_name[] = {
  4,   /* field[4] = cid */
  2,   /* field[2] = forced_fraction */
  0,   /* field[0] = output_json */
  3,   /* field[3] = prompt_tokens */
  1,   /* field[1] = raw_text */
};
static const ProtobufCIntRange fleet__v1__complete_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor fleet__v1__complete_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fleet.v1.CompleteResponse",
  "CompleteResponse",
  "Fleet__V1__CompleteResponse",
  "fleet.v1",
  sizeof(Fleet__V1__CompleteResponse),
  5,
  fleet__v1__complete_response__field_descriptors,
  fleet__v1__complete_response__field_indices_by_name,
  1,  fleet__v1__complete_response__number_ranges,
  (ProtobufCMessageInit) fleet__v1__complete_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor fleet__v1__fleet_lo_ra__method_descriptors[4] =
{
  { "ListAdapters", &fleet__v1__list_adapters_request__descriptor, &fleet__v1__list_adapters_response__descriptor },
  { "AdapterStatus", &fleet__v1__adapter_status_request__descriptor, &fleet__v1__lo_raslot__descriptor },
  { "Train", &fleet__v1__train_request__descriptor, &fleet__v1__train_progress__descriptor },
  { "Complete", &fleet__v1__complete_request__descriptor, &fleet__v1__complete_response__descriptor },
};
const unsigned fleet__v1__fleet_lo_ra__method_indices_by_name[] = {
  1,        /* AdapterStatus */
  3,        /* Complete */
  0,        /* ListAdapters */
  2         /* Train */
};
const ProtobufCServiceDescriptor fleet__v1__fleet_lo_ra__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "fleet.v1.FleetLoRA",
  "FleetLoRA",
  "Fleet__V1__FleetLoRA",
  "fleet.v1",
  4,
  fleet__v1__fleet_lo_ra__method_descriptors,
  fleet__v1__fleet_lo_ra__method_indices_by_name
};
void fleet__v1__fleet_lo_ra__list_adapters(ProtobufCService *service,
                                           const Fleet__V1__ListAdaptersRequest *input,
                                           Fleet__V1__ListAdaptersResponse_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &fleet__v1__fleet_lo_ra__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void fleet__v1__fleet_lo_ra__adapter_status(ProtobufCService *service,
                                            const Fleet__V1__AdapterStatusRequest *input,
                                            Fleet__V1__LoRASlot_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &fleet__v1__fleet_lo_ra__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void fleet__v1__fleet_lo_ra__train(ProtobufCService *service,
                                   const Fleet__V1__TrainRequest *input,
                                   Fleet__V1__TrainProgress_Closure closure,
                                   void *closure_data)
{
  assert(service->descriptor == &fleet__v1__fleet_lo_ra__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void fleet__v1__fleet_lo_ra__complete(ProtobufCService *service,
                                      const Fleet__V1__CompleteRequest *input,
                                      Fleet__V1__CompleteResponse_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &fleet__v1__fleet_lo_ra__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void fleet__v1__fleet_lo_ra__init (Fleet__V1__FleetLoRA_Service *service,
                                   Fleet__V1__FleetLoRA_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &fleet__v1__fleet_lo_ra__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
