/// What of the Mac's pasteboard goes to the Pi: its plain text, unless the app that put it there marked it concealed,
/// transient or generated (nspasteboard.org's markers, which password managers set), and only what the wire carries.
public enum ClipboardText {
    public static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
    ]

    /// `text`: the pasteboard's string; `types`: every type on it.
    public static func shareable(_ text: String?, types: [String]) -> String? {
        guard let text, !text.isEmpty, !types.contains(where: { privateTypes.contains($0) }) else { return nil }
        let bytes = text.utf8
        guard bytes.count <= MaryVNC.clipboardMax, !bytes.contains(0) else { return nil }
        return text
    }
}
