// GENERATED by scripts/gen-lp-tokens.py from maryos/maryui/include/maryui/lp_tokens.h (tokens.json sha256 96e3cd5b4af70144).
// Do not edit: change MaryUI's tokens.json, bump the maryos submodule, then `make lp-tokens`.
import CoreGraphics
import Foundation

// swiftlint:disable all
public enum LP {
    public static let sourceSHA = "96e3cd5b4af70144"
    public static let count = 307
    public enum Platinum {
        /// platinum.0: #f7f7f9
        public static let _0: LPColor = LPColor(red: 0.9686, green: 0.9686, blue: 0.9765, alpha: 1)
        /// platinum.1: #eeeff2
        public static let _1: LPColor = LPColor(red: 0.9333, green: 0.9373, blue: 0.949, alpha: 1)
        /// platinum.2: #e3e5e9
        public static let _2: LPColor = LPColor(red: 0.8902, green: 0.898, blue: 0.9137, alpha: 1)
        /// platinum.3: #d4d7dd
        public static let _3: LPColor = LPColor(red: 0.8314, green: 0.8431, blue: 0.8667, alpha: 1)
        /// platinum.4: #c1c5cd
        public static let _4: LPColor = LPColor(red: 0.7569, green: 0.7725, blue: 0.8039, alpha: 1)
        /// platinum.5: #a9aeb8
        public static let _5: LPColor = LPColor(red: 0.6627, green: 0.6824, blue: 0.7216, alpha: 1)
        /// platinum.6: #8b909b
        public static let _6: LPColor = LPColor(red: 0.5451, green: 0.5647, blue: 0.6078, alpha: 1)
        /// platinum.7: #6b707b
        public static let _7: LPColor = LPColor(red: 0.4196, green: 0.4392, blue: 0.4824, alpha: 1)
        /// platinum.8: #4a4e57
        public static let _8: LPColor = LPColor(red: 0.2902, green: 0.3059, blue: 0.3412, alpha: 1)
        /// platinum.9: #2a2d33
        public static let _9: LPColor = LPColor(red: 0.1647, green: 0.1765, blue: 0.2, alpha: 1)
    }
    public enum Surface {
        /// surface.window-top: #eeeff2
        public static let windowTop: LPColor = LPColor(red: 0.9333, green: 0.9373, blue: 0.949, alpha: 1)
        /// surface.window-bottom: #d4d7dd
        public static let windowBottom: LPColor = LPColor(red: 0.8314, green: 0.8431, blue: 0.8667, alpha: 1)
        /// surface.titlebar-top: #f7f7f9
        public static let titlebarTop: LPColor = LPColor(red: 0.9686, green: 0.9686, blue: 0.9765, alpha: 1)
        /// surface.titlebar-bottom: #c1c5cd
        public static let titlebarBottom: LPColor = LPColor(red: 0.7569, green: 0.7725, blue: 0.8039, alpha: 1)
        /// surface.titlebar-inactive-top: #eeeff2
        public static let titlebarInactiveTop: LPColor = LPColor(red: 0.9333, green: 0.9373, blue: 0.949, alpha: 1)
        /// surface.titlebar-inactive-bottom: #e3e5e9
        public static let titlebarInactiveBottom: LPColor = LPColor(red: 0.8902, green: 0.898, blue: 0.9137, alpha: 1)
        /// surface.menubar-top: #f7f7f9
        public static let menubarTop: LPColor = LPColor(red: 0.9686, green: 0.9686, blue: 0.9765, alpha: 1)
        /// surface.menubar-bottom: #d4d7dd
        public static let menubarBottom: LPColor = LPColor(red: 0.8314, green: 0.8431, blue: 0.8667, alpha: 1)
        /// surface.raised-top: #f7f7f9
        public static let raisedTop: LPColor = LPColor(red: 0.9686, green: 0.9686, blue: 0.9765, alpha: 1)
        /// surface.raised-bottom: #d4d7dd
        public static let raisedBottom: LPColor = LPColor(red: 0.8314, green: 0.8431, blue: 0.8667, alpha: 1)
        /// surface.pressed-top: #c1c5cd
        public static let pressedTop: LPColor = LPColor(red: 0.7569, green: 0.7725, blue: 0.8039, alpha: 1)
        /// surface.pressed-bottom: #d4d7dd
        public static let pressedBottom: LPColor = LPColor(red: 0.8314, green: 0.8431, blue: 0.8667, alpha: 1)
        /// surface.well: #f7f7f9
        public static let well: LPColor = LPColor(red: 0.9686, green: 0.9686, blue: 0.9765, alpha: 1)
        /// surface.body: #f7f7f9
        public static let body: LPColor = LPColor(red: 0.9686, green: 0.9686, blue: 0.9765, alpha: 1)
        /// surface.sidebar: #e3e5e9
        public static let sidebar: LPColor = LPColor(red: 0.8902, green: 0.898, blue: 0.9137, alpha: 1)
        /// surface.menu: rgba(238, 239, 242, 0.94)
        public static let menu: LPColor = LPColor(red: 0.9333, green: 0.9373, blue: 0.949, alpha: 0.94)
        /// surface.selected: rgba(59, 125, 216, 0.16)
        public static let selected: LPColor = LPColor(red: 0.2314, green: 0.4902, blue: 0.8471, alpha: 0.16)
    }
    public enum Ink {
        /// ink.primary: #1f2228
        public static let primary: LPColor = LPColor(red: 0.1216, green: 0.1333, blue: 0.1569, alpha: 1)
        /// ink.secondary: #4a4e57
        public static let secondary: LPColor = LPColor(red: 0.2902, green: 0.3059, blue: 0.3412, alpha: 1)
        /// ink.tertiary: #7a7f8a
        public static let tertiary: LPColor = LPColor(red: 0.4784, green: 0.498, blue: 0.5412, alpha: 1)
        /// ink.disabled: #a9aeb8
        public static let disabled: LPColor = LPColor(red: 0.6627, green: 0.6824, blue: 0.7216, alpha: 1)
        /// ink.inverse: #f7f7f9
        public static let inverse: LPColor = LPColor(red: 0.9686, green: 0.9686, blue: 0.9765, alpha: 1)
        /// ink.on-accent: #ffffff
        public static let onAccent: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 1)
        /// ink.emboss: rgba(255, 255, 255, 0.8)
        public static let emboss: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 0.8)
    }
    public enum Accent {
        public enum Blue {
            /// accent.blue.base: #3b7dd8
            public static let base: LPColor = LPColor(red: 0.2314, green: 0.4902, blue: 0.8471, alpha: 1)
            /// accent.blue.deep: #2a5fae
            public static let deep: LPColor = LPColor(red: 0.1647, green: 0.3725, blue: 0.6824, alpha: 1)
            /// accent.blue.light: #8fb8ee
            public static let light: LPColor = LPColor(red: 0.5608, green: 0.7216, blue: 0.9333, alpha: 1)
            /// accent.blue.soft: rgba(59, 125, 216, 0.18)
            public static let soft: LPColor = LPColor(red: 0.2314, green: 0.4902, blue: 0.8471, alpha: 0.18)
            /// accent.blue.focus-ring: rgba(59, 125, 216, 0.5)
            public static let focusRing: LPColor = LPColor(red: 0.2314, green: 0.4902, blue: 0.8471, alpha: 0.5)
        }
        public enum Graphite {
            /// accent.graphite.base: #6f7683
            public static let base: LPColor = LPColor(red: 0.4353, green: 0.4627, blue: 0.5137, alpha: 1)
            /// accent.graphite.deep: #4f5561
            public static let deep: LPColor = LPColor(red: 0.3098, green: 0.3333, blue: 0.3804, alpha: 1)
            /// accent.graphite.light: #aab0bb
            public static let light: LPColor = LPColor(red: 0.6667, green: 0.6902, blue: 0.7333, alpha: 1)
            /// accent.graphite.soft: rgba(111, 118, 131, 0.2)
            public static let soft: LPColor = LPColor(red: 0.4353, green: 0.4627, blue: 0.5137, alpha: 0.2)
            /// accent.graphite.focus-ring: rgba(111, 118, 131, 0.5)
            public static let focusRing: LPColor = LPColor(red: 0.4353, green: 0.4627, blue: 0.5137, alpha: 0.5)
        }
    }
    public enum Traffic {
        /// traffic.inactive: #c1c5cd
        public static let inactive: LPColor = LPColor(red: 0.7569, green: 0.7725, blue: 0.8039, alpha: 1)
        /// traffic.inactive-deep: #8b909b
        public static let inactiveDeep: LPColor = LPColor(red: 0.5451, green: 0.5647, blue: 0.6078, alpha: 1)
        /// traffic.rim: rgba(0, 0, 0, 0.32)
        public static let rim: LPColor = LPColor(red: 0, green: 0, blue: 0, alpha: 0.32)
        /// traffic.gloss: rgba(255, 255, 255, 0.85)
        public static let gloss: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 0.85)
        /// traffic.bead-shadow: rgba(0, 0, 0, 0.35)
        public static let beadShadow: LPColor = LPColor(red: 0, green: 0, blue: 0, alpha: 0.35)
        public enum Close {
            /// traffic.close.base: #ee6b5f
            public static let base: LPColor = LPColor(red: 0.9333, green: 0.4196, blue: 0.3725, alpha: 1)
            /// traffic.close.deep: #a83a30
            public static let deep: LPColor = LPColor(red: 0.6588, green: 0.2275, blue: 0.1882, alpha: 1)
            /// traffic.close.light: #ffb7ae
            public static let light: LPColor = LPColor(red: 1, green: 0.7176, blue: 0.6824, alpha: 1)
        }
        public enum Minimize {
            /// traffic.minimize.base: #f2bd4f
            public static let base: LPColor = LPColor(red: 0.949, green: 0.7412, blue: 0.3098, alpha: 1)
            /// traffic.minimize.deep: #a6781a
            public static let deep: LPColor = LPColor(red: 0.651, green: 0.4706, blue: 0.102, alpha: 1)
            /// traffic.minimize.light: #ffe6aa
            public static let light: LPColor = LPColor(red: 1, green: 0.902, blue: 0.6667, alpha: 1)
        }
        public enum Zoom {
            /// traffic.zoom.base: #63c657
            public static let base: LPColor = LPColor(red: 0.3882, green: 0.7765, blue: 0.3412, alpha: 1)
            /// traffic.zoom.deep: #2c7f28
            public static let deep: LPColor = LPColor(red: 0.1725, green: 0.498, blue: 0.1569, alpha: 1)
            /// traffic.zoom.light: #bdf2b3
            public static let light: LPColor = LPColor(red: 0.7412, green: 0.949, blue: 0.702, alpha: 1)
        }
    }
    public enum Liquid {
        /// liquid.fill: 0.6
        public static let fill: Double = 0.6
        /// liquid.fill-traffic: 0.72
        public static let fillTraffic: Double = 0.72
        /// liquid.opacity-front: 0.95
        public static let opacityFront: Double = 0.95
        /// liquid.opacity-back: 0.55
        public static let opacityBack: Double = 0.55
        /// liquid.slosh-scale: 1.15
        public static let sloshScale: Double = 1.15
        /// liquid.wave-amplitude: 0.12
        public static let waveAmplitude: Double = 0.12
        /// liquid.wave-period: 3.4s
        public static let wavePeriod: TimeInterval = 3.4
        /// liquid.meniscus: 1px
        public static let meniscus: CGFloat = 1
        /// liquid.surface-light: rgba(255, 255, 255, 0.3)
        public static let surfaceLight: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 0.3)
        /// liquid.surface-depth: 0.16
        public static let surfaceDepth: Double = 0.16
        /// liquid.meniscus-light: rgba(255, 255, 255, 0.72)
        public static let meniscusLight: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 0.72)
        /// liquid.meniscus-shade: rgba(0, 0, 0, 0.28)
        public static let meniscusShade: LPColor = LPColor(red: 0, green: 0, blue: 0, alpha: 0.28)
    }
    public enum Sheen {
        /// sheen.color: #ffffff
        public static let color: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 1)
        /// sheen.alpha: 0.5
        public static let alpha: Double = 0.5
        /// sheen.alpha-inactive: 0.18
        public static let alphaInactive: Double = 0.18
        /// sheen.angle: 105deg
        public static let angle: CGFloat = 105
        /// sheen.light-x: 0.35
        public static let lightX: Double = 0.35
    }
    public enum Molten {
        /// molten.flow: 4
        public static let flow: Double = 4
        /// molten.scale: 0.6
        public static let scale: Double = 0.6
        /// molten.scale-still: 1
        public static let scaleStill: Double = 1
        /// molten.settle-ms: 180ms
        public static let settleMs: TimeInterval = 0.18
        /// molten.max-pixels: 6000000
        public static let maxPixels: Double = 6000000
        /// molten.zoom: 1
        public static let zoom: Double = 1
        public enum Platinum {
            /// molten.platinum.base: #6b7080
            public static let base: LPColor = LPColor(red: 0.4196, green: 0.4392, blue: 0.502, alpha: 1)
            /// molten.platinum.lift: 0.13
            public static let lift: Double = 0.13
            /// molten.platinum.gain: 0.94
            public static let gain: Double = 0.94
            /// molten.platinum.saturation: -0.24
            public static let saturation: Double = -0.24
        }
        public enum Faithful {
            /// molten.faithful.base: #4d4d4d
            public static let base: LPColor = LPColor(red: 0.302, green: 0.302, blue: 0.302, alpha: 1)
            /// molten.faithful.lift: 0
            public static let lift: Double = 0
            /// molten.faithful.gain: 1
            public static let gain: Double = 1
            /// molten.faithful.saturation: -0.4
            public static let saturation: Double = -0.4
        }
    }
    public enum Brush {
        /// brush.opacity: 0.34
        public static let opacity: Double = 0.34
        /// brush.glint: 0.55
        public static let glint: Double = 0.55
        /// brush.contrast: 0.66
        public static let contrast: Double = 0.66
        /// brush.freq-x: 0.02
        public static let freqX: Double = 0.02
        /// brush.freq-y: 0.6
        public static let freqY: Double = 0.6
        /// brush.octaves: 2
        public static let octaves: Double = 2
        /// brush.seed: 7
        public static let seed: Double = 7
        /// brush.tile: 512px
        public static let tile: CGFloat = 512
        public enum Angle {
            /// brush.angle.rise: 1
            public static let rise: Double = 1
            /// brush.angle.run: 2
            public static let run: Double = 2
        }
    }
    public enum Goo {
        /// goo.blur-rest: 2.2
        public static let blurRest: Double = 2.2
        /// goo.blur-flow: 5.5
        public static let blurFlow: Double = 5.5
        /// goo.slope-rest: 26
        public static let slopeRest: Double = 26
        /// goo.slope-flow: 15
        public static let slopeFlow: Double = 15
        /// goo.intercept-rest: -11
        public static let interceptRest: Double = -11
        /// goo.intercept-flow: -6
        public static let interceptFlow: Double = -6
        /// goo.specular-scale: 2.5
        public static let specularScale: Double = 2.5
        /// goo.specular-constant: 0.6
        public static let specularConstant: Double = 0.6
        /// goo.specular-exponent: 30
        public static let specularExponent: Double = 30
        /// goo.specular-elevation: 42
        public static let specularElevation: Double = 42
        /// goo.specular-azimuth: 250
        public static let specularAzimuth: Double = 250
        /// goo.rim-shade: 0.42
        public static let rimShade: Double = 0.42
        /// goo.attract: 3
        public static let attract: Double = 3
        /// goo.lag: 26ms
        public static let lag: TimeInterval = 0.026
        /// goo.stretch: 0.55
        public static let stretch: Double = 0.55
    }
    public enum Edge {
        /// edge.light: rgba(255, 255, 255, 0.78)
        public static let light: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 0.78)
        /// edge.dark: rgba(0, 0, 0, 0.2)
        public static let dark: LPColor = LPColor(red: 0, green: 0, blue: 0, alpha: 0.2)
        /// edge.hairline: rgba(0, 0, 0, 0.32)
        public static let hairline: LPColor = LPColor(red: 0, green: 0, blue: 0, alpha: 0.32)
        /// edge.divider: rgba(0, 0, 0, 0.1)
        public static let divider: LPColor = LPColor(red: 0, green: 0, blue: 0, alpha: 0.1)
    }
    public enum Object {
        /// object.viewbox: 32
        public static let viewbox: Double = 32
        /// object.size-sm: 16px
        public static let sizeSm: CGFloat = 16
        /// object.size-md: 32px
        public static let sizeMd: CGFloat = 32
        /// object.size-lg: 48px
        public static let sizeLg: CGFloat = 48
        /// object.tier-glyph-max: 19px
        public static let tierGlyphMax: CGFloat = 19
        /// object.tier-plain-max: 27px
        public static let tierPlainMax: CGFloat = 27
        /// object.light-azimuth: 250
        public static let lightAzimuth: Double = 250
        /// object.light-elevation: 42
        public static let lightElevation: Double = 42
        /// object.headroom: 0.14
        public static let headroom: Double = 0.14
        /// object.key-alpha: 0.62
        public static let keyAlpha: Double = 0.62
        /// object.key-mid: 0.2
        public static let keyMid: Double = 0.2
        /// object.key-mid-at: 0.3
        public static let keyMidAt: Double = 0.3
        /// object.key-spread: 0.6
        public static let keySpread: Double = 0.6
        /// object.gloss-alpha: 0.45
        public static let glossAlpha: Double = 0.45
        /// object.gloss-shoulder: 0.16
        public static let glossShoulder: Double = 0.16
        /// object.gloss-break: 0.42
        public static let glossBreak: Double = 0.42
        /// object.gloss-bounce: 0.22
        public static let glossBounce: Double = 0.22
        /// object.tone-step: 0.16
        public static let toneStep: Double = 0.16
        /// object.grain-opacity: 0.28
        public static let grainOpacity: Double = 0.28
        /// object.grain-tile: 24
        public static let grainTile: Double = 24
        /// object.rim: rgba(255, 255, 255, 0.78)
        public static let rim: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 0.78)
        /// object.rim-width: 1px
        public static let rimWidth: CGFloat = 1
        /// object.occlusion: rgba(0, 0, 0, 0.2)
        public static let occlusion: LPColor = LPColor(red: 0, green: 0, blue: 0, alpha: 0.2)
        /// object.keyline: rgba(0, 0, 0, 0.32)
        public static let keyline: LPColor = LPColor(red: 0, green: 0, blue: 0, alpha: 0.32)
        /// object.keyline-width: 1px
        public static let keylineWidth: CGFloat = 1
        /// object.contact-dy: 1px
        public static let contactDy: CGFloat = 1
        /// object.contact-blur: 1px
        public static let contactBlur: CGFloat = 1
        /// object.contact-color: rgba(20, 22, 28, 0.34)
        public static let contactColor: LPColor = LPColor(red: 0.0784, green: 0.0863, blue: 0.1098, alpha: 0.34)
        /// object.folder-appearance: slate
        public static let folderAppearance: String = "slate"
        public enum Material {
            public enum Platinum {
                /// object.material.platinum.hi: #f7f7f9
                public static let hi: LPColor = LPColor(red: 0.9686, green: 0.9686, blue: 0.9765, alpha: 1)
                /// object.material.platinum.mid: #e3e5e9
                public static let mid: LPColor = LPColor(red: 0.8902, green: 0.898, blue: 0.9137, alpha: 1)
                /// object.material.platinum.lo: #a9aeb8
                public static let lo: LPColor = LPColor(red: 0.6627, green: 0.6824, blue: 0.7216, alpha: 1)
                /// object.material.platinum.grain: 1
                public static let grain: Double = 1
                /// object.material.platinum.gloss: 0.55
                public static let gloss: Double = 0.55
            }
            public enum Manila {
                /// object.material.manila.hi: #f4e8cc
                public static let hi: LPColor = LPColor(red: 0.9569, green: 0.9098, blue: 0.8, alpha: 1)
                /// object.material.manila.mid: #e2cf9f
                public static let mid: LPColor = LPColor(red: 0.8863, green: 0.8118, blue: 0.6235, alpha: 1)
                /// object.material.manila.lo: #b99f62
                public static let lo: LPColor = LPColor(red: 0.7255, green: 0.6235, blue: 0.3843, alpha: 1)
                /// object.material.manila.grain: 0.35
                public static let grain: Double = 0.35
                /// object.material.manila.gloss: 0.3
                public static let gloss: Double = 0.3
            }
            public enum Slate {
                /// object.material.slate.hi: #d6e0ec
                public static let hi: LPColor = LPColor(red: 0.8392, green: 0.8784, blue: 0.9255, alpha: 1)
                /// object.material.slate.mid: #a9bcd4
                public static let mid: LPColor = LPColor(red: 0.6627, green: 0.7373, blue: 0.8314, alpha: 1)
                /// object.material.slate.lo: #7286a3
                public static let lo: LPColor = LPColor(red: 0.4471, green: 0.5255, blue: 0.6392, alpha: 1)
                /// object.material.slate.grain: 0.3
                public static let grain: Double = 0.3
                /// object.material.slate.gloss: 0.4
                public static let gloss: Double = 0.4
            }
            public enum Paper {
                /// object.material.paper.hi: #ffffff
                public static let hi: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 1)
                /// object.material.paper.mid: #eeeff2
                public static let mid: LPColor = LPColor(red: 0.9333, green: 0.9373, blue: 0.949, alpha: 1)
                /// object.material.paper.lo: #d4d7dd
                public static let lo: LPColor = LPColor(red: 0.8314, green: 0.8431, blue: 0.8667, alpha: 1)
                /// object.material.paper.grain: 0
                public static let grain: Double = 0
                /// object.material.paper.gloss: 0.2
                public static let gloss: Double = 0.2
            }
            public enum Graphite {
                /// object.material.graphite.hi: #a9aeb8
                public static let hi: LPColor = LPColor(red: 0.6627, green: 0.6824, blue: 0.7216, alpha: 1)
                /// object.material.graphite.mid: #6b707b
                public static let mid: LPColor = LPColor(red: 0.4196, green: 0.4392, blue: 0.4824, alpha: 1)
                /// object.material.graphite.lo: #2a2d33
                public static let lo: LPColor = LPColor(red: 0.1647, green: 0.1765, blue: 0.2, alpha: 1)
                /// object.material.graphite.grain: 1
                public static let grain: Double = 1
                /// object.material.graphite.gloss: 0.6
                public static let gloss: Double = 0.6
            }
            public enum Accent {
                /// object.material.accent.hi: #8fb8ee
                public static let hi: LPColor = LPColor(red: 0.5608, green: 0.7216, blue: 0.9333, alpha: 1)
                /// object.material.accent.mid: #3b7dd8
                public static let mid: LPColor = LPColor(red: 0.2314, green: 0.4902, blue: 0.8471, alpha: 1)
                /// object.material.accent.lo: #2a5fae
                public static let lo: LPColor = LPColor(red: 0.1647, green: 0.3725, blue: 0.6824, alpha: 1)
                /// object.material.accent.grain: 0.4
                public static let grain: Double = 0.4
                /// object.material.accent.gloss: 0.75
                public static let gloss: Double = 0.75
            }
            public enum Ruby {
                /// object.material.ruby.hi: #ffb7ae
                public static let hi: LPColor = LPColor(red: 1, green: 0.7176, blue: 0.6824, alpha: 1)
                /// object.material.ruby.mid: #ee6b5f
                public static let mid: LPColor = LPColor(red: 0.9333, green: 0.4196, blue: 0.3725, alpha: 1)
                /// object.material.ruby.lo: #a83a30
                public static let lo: LPColor = LPColor(red: 0.6588, green: 0.2275, blue: 0.1882, alpha: 1)
                /// object.material.ruby.grain: 0
                public static let grain: Double = 0
                /// object.material.ruby.gloss: 0.9
                public static let gloss: Double = 0.9
            }
            public enum Amber {
                /// object.material.amber.hi: #ffe6aa
                public static let hi: LPColor = LPColor(red: 1, green: 0.902, blue: 0.6667, alpha: 1)
                /// object.material.amber.mid: #f2bd4f
                public static let mid: LPColor = LPColor(red: 0.949, green: 0.7412, blue: 0.3098, alpha: 1)
                /// object.material.amber.lo: #a6781a
                public static let lo: LPColor = LPColor(red: 0.651, green: 0.4706, blue: 0.102, alpha: 1)
                /// object.material.amber.grain: 0
                public static let grain: Double = 0
                /// object.material.amber.gloss: 0.9
                public static let gloss: Double = 0.9
            }
            public enum Verdant {
                /// object.material.verdant.hi: #bdf2b3
                public static let hi: LPColor = LPColor(red: 0.7412, green: 0.949, blue: 0.702, alpha: 1)
                /// object.material.verdant.mid: #63c657
                public static let mid: LPColor = LPColor(red: 0.3882, green: 0.7765, blue: 0.3412, alpha: 1)
                /// object.material.verdant.lo: #2c7f28
                public static let lo: LPColor = LPColor(red: 0.1725, green: 0.498, blue: 0.1569, alpha: 1)
                /// object.material.verdant.grain: 0
                public static let grain: Double = 0
                /// object.material.verdant.gloss: 0.9
                public static let gloss: Double = 0.9
            }
            public enum Glass {
                /// object.material.glass.hi: #ffffff
                public static let hi: LPColor = LPColor(red: 1, green: 1, blue: 1, alpha: 1)
                /// object.material.glass.mid: #cfe0f5
                public static let mid: LPColor = LPColor(red: 0.8118, green: 0.8784, blue: 0.9608, alpha: 1)
                /// object.material.glass.lo: #7d9dc4
                public static let lo: LPColor = LPColor(red: 0.4902, green: 0.6157, blue: 0.7686, alpha: 1)
                /// object.material.glass.grain: 0
                public static let grain: Double = 0
                /// object.material.glass.gloss: 1
                public static let gloss: Double = 1
            }
            public enum Folder {
                /// object.material.folder.hi: #f4e8cc
                public static let hi: LPColor = LPColor(red: 0.9569, green: 0.9098, blue: 0.8, alpha: 1)
                /// object.material.folder.mid: #e2cf9f
                public static let mid: LPColor = LPColor(red: 0.8863, green: 0.8118, blue: 0.6235, alpha: 1)
                /// object.material.folder.lo: #b99f62
                public static let lo: LPColor = LPColor(red: 0.7255, green: 0.6235, blue: 0.3843, alpha: 1)
                /// object.material.folder.grain: 0.35
                public static let grain: Double = 0.35
                /// object.material.folder.gloss: 0.3
                public static let gloss: Double = 0.3
            }
        }
    }
    public enum Radius {
        /// radius.xs: 4px
        public static let xs: CGFloat = 4
        /// radius.sm: 6px
        public static let sm: CGFloat = 6
        /// radius.md: 10px
        public static let md: CGFloat = 10
        /// radius.lg: 14px
        public static let lg: CGFloat = 14
        /// radius.window: 12px
        public static let window: CGFloat = 12
        /// radius.window-min: 8px
        public static let windowMin: CGFloat = 8
        /// radius.window-max: 16px
        public static let windowMax: CGFloat = 16
        /// radius.spotlight: 30px
        public static let spotlight: CGFloat = 30
        /// radius.spotlight-menu: 14px
        public static let spotlightMenu: CGFloat = 14
        /// radius.spotlight-results: 18px
        public static let spotlightResults: CGFloat = 18
        /// radius.pill: 999px
        public static let pill: CGFloat = 999
    }
    public enum RadiusFlex {
        /// radius-flex.spread: 6
        public static let spread: Double = 6
        /// radius-flex.velocity-ref: 1100
        public static let velocityRef: Double = 1100
        /// radius-flex.gamma: 0.7
        public static let gamma: Double = 0.7
        /// radius-flex.impulse: 26
        public static let impulse: Double = 26
        /// radius-flex.base: 1
        public static let base: Double = 1
        /// radius-flex.span: 0.35
        public static let span: Double = 0.35
        /// radius-flex.press: 1.35
        public static let press: Double = 1.35
    }
    public enum Shadow {
        /// shadow.window: 0 14px 36px 0 rgba(20, 22, 28, 0.26), 0 0 0 1px rgba(0, 0...
        public static let window: [LPShadowLayer] = [LPShadowLayer(inset: false, x: 0, y: 14, blur: 36, spread: 0, color: LPColor(red: 0.0784, green: 0.0863, blue: 0.1098, alpha: 0.26)), LPShadowLayer(inset: false, x: 0, y: 0, blur: 0, spread: 1, color: LPColor(red: 0, green: 0, blue: 0, alpha: 0.28))]
        /// shadow.window-focused: 0 24px 56px 0 rgba(20, 22, 28, 0.4), 0 0 0 1px rgba(0, 0,...
        public static let windowFocused: [LPShadowLayer] = [LPShadowLayer(inset: false, x: 0, y: 24, blur: 56, spread: 0, color: LPColor(red: 0.0784, green: 0.0863, blue: 0.1098, alpha: 0.4)), LPShadowLayer(inset: false, x: 0, y: 0, blur: 0, spread: 1, color: LPColor(red: 0, green: 0, blue: 0, alpha: 0.34))]
        /// shadow.menu: 0 10px 30px 0 rgba(20, 22, 28, 0.3), 0 0 0 1px rgba(0, 0,...
        public static let menu: [LPShadowLayer] = [LPShadowLayer(inset: false, x: 0, y: 10, blur: 30, spread: 0, color: LPColor(red: 0.0784, green: 0.0863, blue: 0.1098, alpha: 0.3)), LPShadowLayer(inset: false, x: 0, y: 0, blur: 0, spread: 1, color: LPColor(red: 0, green: 0, blue: 0, alpha: 0.22))]
        /// shadow.emboss-raised: inset 0 1px 0 0 rgba(255, 255, 255, 0.78), inset 0 -1px 0...
        public static let embossRaised: [LPShadowLayer] = [LPShadowLayer(inset: true, x: 0, y: 1, blur: 0, spread: 0, color: LPColor(red: 1, green: 1, blue: 1, alpha: 0.78)), LPShadowLayer(inset: true, x: 0, y: -1, blur: 0, spread: 0, color: LPColor(red: 0, green: 0, blue: 0, alpha: 0.2))]
        /// shadow.emboss-well: inset 0 1px 3px 0 rgba(0, 0, 0, 0.28), inset 0 0 0 1px rg...
        public static let embossWell: [LPShadowLayer] = [LPShadowLayer(inset: true, x: 0, y: 1, blur: 3, spread: 0, color: LPColor(red: 0, green: 0, blue: 0, alpha: 0.28)), LPShadowLayer(inset: true, x: 0, y: 0, blur: 0, spread: 1, color: LPColor(red: 0, green: 0, blue: 0, alpha: 0.12))]
        /// shadow.emboss-pressed: inset 0 2px 4px 0 rgba(0, 0, 0, 0.3)
        public static let embossPressed: [LPShadowLayer] = [LPShadowLayer(inset: true, x: 0, y: 2, blur: 4, spread: 0, color: LPColor(red: 0, green: 0, blue: 0, alpha: 0.3))]
    }
    public enum Space {
        /// space.1: 4px
        public static let _1: CGFloat = 4
        /// space.2: 8px
        public static let _2: CGFloat = 8
        /// space.3: 12px
        public static let _3: CGFloat = 12
        /// space.4: 16px
        public static let _4: CGFloat = 16
        /// space.5: 20px
        public static let _5: CGFloat = 20
        /// space.6: 24px
        public static let _6: CGFloat = 24
        /// space.7: 32px
        public static let _7: CGFloat = 32
        /// space.8: 40px
        public static let _8: CGFloat = 40
    }
    public enum Size {
        /// size.menubar-height: 24px
        public static let menubarHeight: CGFloat = 24
        /// size.titlebar-height: 42px
        public static let titlebarHeight: CGFloat = 42
        /// size.titlebar-title-inset: 90px
        public static let titlebarTitleInset: CGFloat = 90
        /// size.traffic: 18px
        public static let traffic: CGFloat = 18
        /// size.traffic-gap: 10px
        public static let trafficGap: CGFloat = 10
        /// size.control-height: 22px
        public static let controlHeight: CGFloat = 22
        /// size.control-height-sm: 18px
        public static let controlHeightSm: CGFloat = 18
        /// size.segmented-height: 28px
        public static let segmentedHeight: CGFloat = 28
        /// size.segmented-height-sm: 22px
        public static let segmentedHeightSm: CGFloat = 22
        /// size.segmented-pad: 3px
        public static let segmentedPad: CGFloat = 3
        /// size.resize-grip: 6px
        public static let resizeGrip: CGFloat = 6
        /// size.resize-corner: 14px
        public static let resizeCorner: CGFloat = 14
        /// size.window-min-w: 240px
        public static let windowMinW: CGFloat = 240
        /// size.window-min-h: 160px
        public static let windowMinH: CGFloat = 160
        /// size.spotlight-width: 560px
        public static let spotlightWidth: CGFloat = 560
        /// size.spotlight-bar-height: 44px
        public static let spotlightBarHeight: CGFloat = 44
        /// size.spotlight-tile: 56px
        public static let spotlightTile: CGFloat = 56
        /// size.spotlight-cell: 96px
        public static let spotlightCell: CGFloat = 96
        /// size.spotlight-chat: 320px
        public static let spotlightChat: CGFloat = 320
        /// size.spotlight-accessory: 28px
        public static let spotlightAccessory: CGFloat = 28
    }
    public enum Font {
        /// font.ui: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvet...
        public static let ui: [String] = ["-apple-system", "BlinkMacSystemFont", "SF Pro Text", "Helvetica Neue", "Helvetica", "Arial", "Inter", "sans-serif"]
        /// font.display: "Iowan Old Style", "Palatino Linotype", Palatino, Georgia...
        public static let display: [String] = ["Iowan Old Style", "Palatino Linotype", "Palatino", "Georgia", "P052", "serif"]
        /// font.mono: SFMono-Regular, ui-monospace, Menlo, Consolas, "JetBrains...
        public static let mono: [String] = ["SFMono-Regular", "ui-monospace", "Menlo", "Consolas", "JetBrains Mono", "monospace"]
    }
    public enum Text {
        /// text.xs: 11px
        public static let xs: CGFloat = 11
        /// text.sm: 12px
        public static let sm: CGFloat = 12
        /// text.md: 13px
        public static let md: CGFloat = 13
        /// text.lg: 15px
        public static let lg: CGFloat = 15
        /// text.xl: 20px
        public static let xl: CGFloat = 20
        /// text.xxl: 28px
        public static let xxl: CGFloat = 28
        /// text.weight-regular: 400
        public static let weightRegular: Int = 400
        /// text.weight-medium: 500
        public static let weightMedium: Int = 500
        /// text.weight-semibold: 600
        public static let weightSemibold: Int = 600
        /// text.weight-bold: 700
        public static let weightBold: Int = 700
        /// text.leading-tight: 1.2
        public static let leadingTight: Double = 1.2
        /// text.leading-normal: 1.45
        public static let leadingNormal: Double = 1.45
    }
    public enum Motion {
        /// motion.fast: 120ms
        public static let fast: TimeInterval = 0.12
        /// motion.normal: 200ms
        public static let normal: TimeInterval = 0.2
        /// motion.slow: 360ms
        public static let slow: TimeInterval = 0.36
        /// motion.ease-out: cubic-bezier(0.2, 0.8, 0.2, 1)
        public static let easeOut: LPCubicBezier = LPCubicBezier(x1: 0.2, y1: 0.8, x2: 0.2, y2: 1)
        /// motion.ease-spring: cubic-bezier(0.34, 1.56, 0.64, 1)
        public static let easeSpring: LPCubicBezier = LPCubicBezier(x1: 0.34, y1: 1.56, x2: 0.64, y2: 1)
        /// motion.radius-detune: 0.08
        public static let radiusDetune: Double = 0.08
        /// motion.slosh-frequency: 1.3
        public static let sloshFrequency: Double = 1.3
        /// motion.slosh-damping: 0.16
        public static let sloshDamping: Double = 0.16
        /// motion.slosh-gain: 0.0009
        public static let sloshGain: Double = 0.0009
        /// motion.slosh-max: 0.5
        public static let sloshMax: Double = 0.5
        /// motion.slosh-max-accel: 12000
        public static let sloshMaxAccel: Double = 12000
        /// motion.slosh-lift: 10
        public static let sloshLift: Double = 10
        /// motion.slosh-shift: 7
        public static let sloshShift: Double = 7
        /// motion.slosh-velocity-ref: 1200
        public static let sloshVelocityRef: Double = 1200
        /// motion.slosh-shear-gain: 18
        public static let sloshShearGain: Double = 18
        /// motion.slosh-shear-gamma: 0.7
        public static let sloshShearGamma: Double = 0.7
        /// motion.jelly-max-scale: 0.035
        public static let jellyMaxScale: Double = 0.035
        /// motion.jelly-max-skew: 2.5
        public static let jellyMaxSkew: Double = 2.5
        /// motion.tilt-max: 3
        public static let tiltMax: Double = 3
        /// motion.velocity-ref: 2500
        public static let velocityRef: Double = 2500
        /// motion.drift-period: 45s
        public static let driftPeriod: TimeInterval = 45
        public enum SpringSheen {
            /// motion.spring-sheen.frequency: 1.2
            public static let frequency: Double = 1.2
            /// motion.spring-sheen.damping: 0.45
            public static let damping: Double = 0.45
        }
        public enum SpringTilt {
            /// motion.spring-tilt.frequency: 1.6
            public static let frequency: Double = 1.6
            /// motion.spring-tilt.damping: 0.6
            public static let damping: Double = 0.6
        }
        public enum SpringJelly {
            /// motion.spring-jelly.frequency: 2.2
            public static let frequency: Double = 2.2
            /// motion.spring-jelly.damping: 0.55
            public static let damping: Double = 0.55
        }
        public enum SpringFly {
            /// motion.spring-fly.frequency: 2.3
            public static let frequency: Double = 2.3
            /// motion.spring-fly.damping: 0.8
            public static let damping: Double = 0.8
        }
        public enum SpringRadius {
            /// motion.spring-radius.frequency: 2.6
            public static let frequency: Double = 2.6
            /// motion.spring-radius.damping: 0.35
            public static let damping: Double = 0.35
        }
        public enum SpringVxLag {
            /// motion.spring-vx-lag.frequency: 0.9
            public static let frequency: Double = 0.9
            /// motion.spring-vx-lag.damping: 0.9
            public static let damping: Double = 0.9
        }
    }
    public enum Z {
        /// z.wallpaper: 0
        public static let wallpaper: Double = 0
        /// z.windows: 100
        public static let windows: Double = 100
        /// z.menubar: 600
        public static let menubar: Double = 600
        /// z.menus: 700
        public static let menus: Double = 700
        /// z.spotlight: 800
        public static let spotlight: Double = 800
    }

    /// Every token as the header lists it, for tests and the About panel.
    public static let all: [LPTokenInfo] = [
        LPTokenInfo("platinum.0", "color", "#f7f7f9"),
        LPTokenInfo("platinum.1", "color", "#eeeff2"),
        LPTokenInfo("platinum.2", "color", "#e3e5e9"),
        LPTokenInfo("platinum.3", "color", "#d4d7dd"),
        LPTokenInfo("platinum.4", "color", "#c1c5cd"),
        LPTokenInfo("platinum.5", "color", "#a9aeb8"),
        LPTokenInfo("platinum.6", "color", "#8b909b"),
        LPTokenInfo("platinum.7", "color", "#6b707b"),
        LPTokenInfo("platinum.8", "color", "#4a4e57"),
        LPTokenInfo("platinum.9", "color", "#2a2d33"),
        LPTokenInfo("surface.window-top", "color", "#eeeff2"),
        LPTokenInfo("surface.window-bottom", "color", "#d4d7dd"),
        LPTokenInfo("surface.titlebar-top", "color", "#f7f7f9"),
        LPTokenInfo("surface.titlebar-bottom", "color", "#c1c5cd"),
        LPTokenInfo("surface.titlebar-inactive-top", "color", "#eeeff2"),
        LPTokenInfo("surface.titlebar-inactive-bottom", "color", "#e3e5e9"),
        LPTokenInfo("surface.menubar-top", "color", "#f7f7f9"),
        LPTokenInfo("surface.menubar-bottom", "color", "#d4d7dd"),
        LPTokenInfo("surface.raised-top", "color", "#f7f7f9"),
        LPTokenInfo("surface.raised-bottom", "color", "#d4d7dd"),
        LPTokenInfo("surface.pressed-top", "color", "#c1c5cd"),
        LPTokenInfo("surface.pressed-bottom", "color", "#d4d7dd"),
        LPTokenInfo("surface.well", "color", "#f7f7f9"),
        LPTokenInfo("surface.body", "color", "#f7f7f9"),
        LPTokenInfo("surface.sidebar", "color", "#e3e5e9"),
        LPTokenInfo("surface.menu", "color", "rgba(238, 239, 242, 0.94)"),
        LPTokenInfo("surface.selected", "color", "rgba(59, 125, 216, 0.16)"),
        LPTokenInfo("ink.primary", "color", "#1f2228"),
        LPTokenInfo("ink.secondary", "color", "#4a4e57"),
        LPTokenInfo("ink.tertiary", "color", "#7a7f8a"),
        LPTokenInfo("ink.disabled", "color", "#a9aeb8"),
        LPTokenInfo("ink.inverse", "color", "#f7f7f9"),
        LPTokenInfo("ink.on-accent", "color", "#ffffff"),
        LPTokenInfo("ink.emboss", "color", "rgba(255, 255, 255, 0.8)"),
        LPTokenInfo("accent.blue.base", "color", "#3b7dd8"),
        LPTokenInfo("accent.blue.deep", "color", "#2a5fae"),
        LPTokenInfo("accent.blue.light", "color", "#8fb8ee"),
        LPTokenInfo("accent.blue.soft", "color", "rgba(59, 125, 216, 0.18)"),
        LPTokenInfo("accent.blue.focus-ring", "color", "rgba(59, 125, 216, 0.5)"),
        LPTokenInfo("accent.graphite.base", "color", "#6f7683"),
        LPTokenInfo("accent.graphite.deep", "color", "#4f5561"),
        LPTokenInfo("accent.graphite.light", "color", "#aab0bb"),
        LPTokenInfo("accent.graphite.soft", "color", "rgba(111, 118, 131, 0.2)"),
        LPTokenInfo("accent.graphite.focus-ring", "color", "rgba(111, 118, 131, 0.5)"),
        LPTokenInfo("traffic.close.base", "color", "#ee6b5f"),
        LPTokenInfo("traffic.close.deep", "color", "#a83a30"),
        LPTokenInfo("traffic.close.light", "color", "#ffb7ae"),
        LPTokenInfo("traffic.minimize.base", "color", "#f2bd4f"),
        LPTokenInfo("traffic.minimize.deep", "color", "#a6781a"),
        LPTokenInfo("traffic.minimize.light", "color", "#ffe6aa"),
        LPTokenInfo("traffic.zoom.base", "color", "#63c657"),
        LPTokenInfo("traffic.zoom.deep", "color", "#2c7f28"),
        LPTokenInfo("traffic.zoom.light", "color", "#bdf2b3"),
        LPTokenInfo("traffic.inactive", "color", "#c1c5cd"),
        LPTokenInfo("traffic.inactive-deep", "color", "#8b909b"),
        LPTokenInfo("traffic.rim", "color", "rgba(0, 0, 0, 0.32)"),
        LPTokenInfo("traffic.gloss", "color", "rgba(255, 255, 255, 0.85)"),
        LPTokenInfo("traffic.bead-shadow", "color", "rgba(0, 0, 0, 0.35)"),
        LPTokenInfo("liquid.fill", "number", "0.6"),
        LPTokenInfo("liquid.fill-traffic", "number", "0.72"),
        LPTokenInfo("liquid.opacity-front", "number", "0.95"),
        LPTokenInfo("liquid.opacity-back", "number", "0.55"),
        LPTokenInfo("liquid.slosh-scale", "number", "1.15"),
        LPTokenInfo("liquid.wave-amplitude", "number", "0.12"),
        LPTokenInfo("liquid.wave-period", "duration", "3.4s"),
        LPTokenInfo("liquid.meniscus", "dimension", "1px"),
        LPTokenInfo("liquid.surface-light", "color", "rgba(255, 255, 255, 0.3)"),
        LPTokenInfo("liquid.surface-depth", "number", "0.16"),
        LPTokenInfo("liquid.meniscus-light", "color", "rgba(255, 255, 255, 0.72)"),
        LPTokenInfo("liquid.meniscus-shade", "color", "rgba(0, 0, 0, 0.28)"),
        LPTokenInfo("sheen.color", "color", "#ffffff"),
        LPTokenInfo("sheen.alpha", "number", "0.5"),
        LPTokenInfo("sheen.alpha-inactive", "number", "0.18"),
        LPTokenInfo("sheen.angle", "dimension", "105deg"),
        LPTokenInfo("sheen.light-x", "number", "0.35"),
        LPTokenInfo("molten.flow", "number", "4"),
        LPTokenInfo("molten.scale", "number", "0.6"),
        LPTokenInfo("molten.scale-still", "number", "1"),
        LPTokenInfo("molten.settle-ms", "duration", "180ms"),
        LPTokenInfo("molten.max-pixels", "number", "6000000"),
        LPTokenInfo("molten.zoom", "number", "1"),
        LPTokenInfo("molten.platinum.base", "color", "#6b7080"),
        LPTokenInfo("molten.platinum.lift", "number", "0.13"),
        LPTokenInfo("molten.platinum.gain", "number", "0.94"),
        LPTokenInfo("molten.platinum.saturation", "number", "-0.24"),
        LPTokenInfo("molten.faithful.base", "color", "#4d4d4d"),
        LPTokenInfo("molten.faithful.lift", "number", "0"),
        LPTokenInfo("molten.faithful.gain", "number", "1"),
        LPTokenInfo("molten.faithful.saturation", "number", "-0.4"),
        LPTokenInfo("brush.opacity", "number", "0.34"),
        LPTokenInfo("brush.glint", "number", "0.55"),
        LPTokenInfo("brush.contrast", "number", "0.66"),
        LPTokenInfo("brush.freq-x", "number", "0.02"),
        LPTokenInfo("brush.freq-y", "number", "0.6"),
        LPTokenInfo("brush.octaves", "number", "2"),
        LPTokenInfo("brush.seed", "number", "7"),
        LPTokenInfo("brush.tile", "dimension", "512px"),
        LPTokenInfo("brush.angle.rise", "number", "1"),
        LPTokenInfo("brush.angle.run", "number", "2"),
        LPTokenInfo("goo.blur-rest", "number", "2.2"),
        LPTokenInfo("goo.blur-flow", "number", "5.5"),
        LPTokenInfo("goo.slope-rest", "number", "26"),
        LPTokenInfo("goo.slope-flow", "number", "15"),
        LPTokenInfo("goo.intercept-rest", "number", "-11"),
        LPTokenInfo("goo.intercept-flow", "number", "-6"),
        LPTokenInfo("goo.specular-scale", "number", "2.5"),
        LPTokenInfo("goo.specular-constant", "number", "0.6"),
        LPTokenInfo("goo.specular-exponent", "number", "30"),
        LPTokenInfo("goo.specular-elevation", "number", "42"),
        LPTokenInfo("goo.specular-azimuth", "number", "250"),
        LPTokenInfo("goo.rim-shade", "number", "0.42"),
        LPTokenInfo("goo.attract", "number", "3"),
        LPTokenInfo("goo.lag", "duration", "26ms"),
        LPTokenInfo("goo.stretch", "number", "0.55"),
        LPTokenInfo("edge.light", "color", "rgba(255, 255, 255, 0.78)"),
        LPTokenInfo("edge.dark", "color", "rgba(0, 0, 0, 0.2)"),
        LPTokenInfo("edge.hairline", "color", "rgba(0, 0, 0, 0.32)"),
        LPTokenInfo("edge.divider", "color", "rgba(0, 0, 0, 0.1)"),
        LPTokenInfo("object.viewbox", "number", "32"),
        LPTokenInfo("object.size-sm", "dimension", "16px"),
        LPTokenInfo("object.size-md", "dimension", "32px"),
        LPTokenInfo("object.size-lg", "dimension", "48px"),
        LPTokenInfo("object.tier-glyph-max", "dimension", "19px"),
        LPTokenInfo("object.tier-plain-max", "dimension", "27px"),
        LPTokenInfo("object.light-azimuth", "number", "250"),
        LPTokenInfo("object.light-elevation", "number", "42"),
        LPTokenInfo("object.headroom", "number", "0.14"),
        LPTokenInfo("object.key-alpha", "number", "0.62"),
        LPTokenInfo("object.key-mid", "number", "0.2"),
        LPTokenInfo("object.key-mid-at", "number", "0.3"),
        LPTokenInfo("object.key-spread", "number", "0.6"),
        LPTokenInfo("object.gloss-alpha", "number", "0.45"),
        LPTokenInfo("object.gloss-shoulder", "number", "0.16"),
        LPTokenInfo("object.gloss-break", "number", "0.42"),
        LPTokenInfo("object.gloss-bounce", "number", "0.22"),
        LPTokenInfo("object.tone-step", "number", "0.16"),
        LPTokenInfo("object.grain-opacity", "number", "0.28"),
        LPTokenInfo("object.grain-tile", "number", "24"),
        LPTokenInfo("object.rim", "color", "rgba(255, 255, 255, 0.78)"),
        LPTokenInfo("object.rim-width", "dimension", "1px"),
        LPTokenInfo("object.occlusion", "color", "rgba(0, 0, 0, 0.2)"),
        LPTokenInfo("object.keyline", "color", "rgba(0, 0, 0, 0.32)"),
        LPTokenInfo("object.keyline-width", "dimension", "1px"),
        LPTokenInfo("object.contact-dy", "dimension", "1px"),
        LPTokenInfo("object.contact-blur", "dimension", "1px"),
        LPTokenInfo("object.contact-color", "color", "rgba(20, 22, 28, 0.34)"),
        LPTokenInfo("object.material.platinum.hi", "color", "#f7f7f9"),
        LPTokenInfo("object.material.platinum.mid", "color", "#e3e5e9"),
        LPTokenInfo("object.material.platinum.lo", "color", "#a9aeb8"),
        LPTokenInfo("object.material.platinum.grain", "number", "1"),
        LPTokenInfo("object.material.platinum.gloss", "number", "0.55"),
        LPTokenInfo("object.material.manila.hi", "color", "#f4e8cc"),
        LPTokenInfo("object.material.manila.mid", "color", "#e2cf9f"),
        LPTokenInfo("object.material.manila.lo", "color", "#b99f62"),
        LPTokenInfo("object.material.manila.grain", "number", "0.35"),
        LPTokenInfo("object.material.manila.gloss", "number", "0.3"),
        LPTokenInfo("object.material.slate.hi", "color", "#d6e0ec"),
        LPTokenInfo("object.material.slate.mid", "color", "#a9bcd4"),
        LPTokenInfo("object.material.slate.lo", "color", "#7286a3"),
        LPTokenInfo("object.material.slate.grain", "number", "0.3"),
        LPTokenInfo("object.material.slate.gloss", "number", "0.4"),
        LPTokenInfo("object.material.paper.hi", "color", "#ffffff"),
        LPTokenInfo("object.material.paper.mid", "color", "#eeeff2"),
        LPTokenInfo("object.material.paper.lo", "color", "#d4d7dd"),
        LPTokenInfo("object.material.paper.grain", "number", "0"),
        LPTokenInfo("object.material.paper.gloss", "number", "0.2"),
        LPTokenInfo("object.material.graphite.hi", "color", "#a9aeb8"),
        LPTokenInfo("object.material.graphite.mid", "color", "#6b707b"),
        LPTokenInfo("object.material.graphite.lo", "color", "#2a2d33"),
        LPTokenInfo("object.material.graphite.grain", "number", "1"),
        LPTokenInfo("object.material.graphite.gloss", "number", "0.6"),
        LPTokenInfo("object.material.accent.hi", "color", "#8fb8ee"),
        LPTokenInfo("object.material.accent.mid", "color", "#3b7dd8"),
        LPTokenInfo("object.material.accent.lo", "color", "#2a5fae"),
        LPTokenInfo("object.material.accent.grain", "number", "0.4"),
        LPTokenInfo("object.material.accent.gloss", "number", "0.75"),
        LPTokenInfo("object.material.ruby.hi", "color", "#ffb7ae"),
        LPTokenInfo("object.material.ruby.mid", "color", "#ee6b5f"),
        LPTokenInfo("object.material.ruby.lo", "color", "#a83a30"),
        LPTokenInfo("object.material.ruby.grain", "number", "0"),
        LPTokenInfo("object.material.ruby.gloss", "number", "0.9"),
        LPTokenInfo("object.material.amber.hi", "color", "#ffe6aa"),
        LPTokenInfo("object.material.amber.mid", "color", "#f2bd4f"),
        LPTokenInfo("object.material.amber.lo", "color", "#a6781a"),
        LPTokenInfo("object.material.amber.grain", "number", "0"),
        LPTokenInfo("object.material.amber.gloss", "number", "0.9"),
        LPTokenInfo("object.material.verdant.hi", "color", "#bdf2b3"),
        LPTokenInfo("object.material.verdant.mid", "color", "#63c657"),
        LPTokenInfo("object.material.verdant.lo", "color", "#2c7f28"),
        LPTokenInfo("object.material.verdant.grain", "number", "0"),
        LPTokenInfo("object.material.verdant.gloss", "number", "0.9"),
        LPTokenInfo("object.material.glass.hi", "color", "#ffffff"),
        LPTokenInfo("object.material.glass.mid", "color", "#cfe0f5"),
        LPTokenInfo("object.material.glass.lo", "color", "#7d9dc4"),
        LPTokenInfo("object.material.glass.grain", "number", "0"),
        LPTokenInfo("object.material.glass.gloss", "number", "1"),
        LPTokenInfo("object.material.folder.hi", "color", "#f4e8cc"),
        LPTokenInfo("object.material.folder.mid", "color", "#e2cf9f"),
        LPTokenInfo("object.material.folder.lo", "color", "#b99f62"),
        LPTokenInfo("object.material.folder.grain", "number", "0.35"),
        LPTokenInfo("object.material.folder.gloss", "number", "0.3"),
        LPTokenInfo("object.folder-appearance", "string", "slate"),
        LPTokenInfo("radius.xs", "dimension", "4px"),
        LPTokenInfo("radius.sm", "dimension", "6px"),
        LPTokenInfo("radius.md", "dimension", "10px"),
        LPTokenInfo("radius.lg", "dimension", "14px"),
        LPTokenInfo("radius.window", "dimension", "12px"),
        LPTokenInfo("radius.window-min", "dimension", "8px"),
        LPTokenInfo("radius.window-max", "dimension", "16px"),
        LPTokenInfo("radius.spotlight", "dimension", "30px"),
        LPTokenInfo("radius.spotlight-menu", "dimension", "14px"),
        LPTokenInfo("radius.spotlight-results", "dimension", "18px"),
        LPTokenInfo("radius.pill", "dimension", "999px"),
        LPTokenInfo("radius-flex.spread", "number", "6"),
        LPTokenInfo("radius-flex.velocity-ref", "number", "1100"),
        LPTokenInfo("radius-flex.gamma", "number", "0.7"),
        LPTokenInfo("radius-flex.impulse", "number", "26"),
        LPTokenInfo("radius-flex.base", "number", "1"),
        LPTokenInfo("radius-flex.span", "number", "0.35"),
        LPTokenInfo("radius-flex.press", "number", "1.35"),
        LPTokenInfo("shadow.window", "shadow", "0 14px 36px 0 rgba(20, 22, 28, 0.26), 0 0 0 1px rgba(0, 0, 0, 0.28)"),
        LPTokenInfo("shadow.window-focused", "shadow", "0 24px 56px 0 rgba(20, 22, 28, 0.4), 0 0 0 1px rgba(0, 0, 0, 0.34)"),
        LPTokenInfo("shadow.menu", "shadow", "0 10px 30px 0 rgba(20, 22, 28, 0.3), 0 0 0 1px rgba(0, 0, 0, 0.22)"),
        LPTokenInfo("shadow.emboss-raised", "shadow", "inset 0 1px 0 0 rgba(255, 255, 255, 0.78), inset 0 -1px 0 0 rgba(0, 0, 0, 0.2)"),
        LPTokenInfo("shadow.emboss-well", "shadow", "inset 0 1px 3px 0 rgba(0, 0, 0, 0.28), inset 0 0 0 1px rgba(0, 0, 0, 0.12)"),
        LPTokenInfo("shadow.emboss-pressed", "shadow", "inset 0 2px 4px 0 rgba(0, 0, 0, 0.3)"),
        LPTokenInfo("space.1", "dimension", "4px"),
        LPTokenInfo("space.2", "dimension", "8px"),
        LPTokenInfo("space.3", "dimension", "12px"),
        LPTokenInfo("space.4", "dimension", "16px"),
        LPTokenInfo("space.5", "dimension", "20px"),
        LPTokenInfo("space.6", "dimension", "24px"),
        LPTokenInfo("space.7", "dimension", "32px"),
        LPTokenInfo("space.8", "dimension", "40px"),
        LPTokenInfo("size.menubar-height", "dimension", "24px"),
        LPTokenInfo("size.titlebar-height", "dimension", "42px"),
        LPTokenInfo("size.titlebar-title-inset", "dimension", "90px"),
        LPTokenInfo("size.traffic", "dimension", "18px"),
        LPTokenInfo("size.traffic-gap", "dimension", "10px"),
        LPTokenInfo("size.control-height", "dimension", "22px"),
        LPTokenInfo("size.control-height-sm", "dimension", "18px"),
        LPTokenInfo("size.segmented-height", "dimension", "28px"),
        LPTokenInfo("size.segmented-height-sm", "dimension", "22px"),
        LPTokenInfo("size.segmented-pad", "dimension", "3px"),
        LPTokenInfo("size.resize-grip", "dimension", "6px"),
        LPTokenInfo("size.resize-corner", "dimension", "14px"),
        LPTokenInfo("size.window-min-w", "dimension", "240px"),
        LPTokenInfo("size.window-min-h", "dimension", "160px"),
        LPTokenInfo("size.spotlight-width", "dimension", "560px"),
        LPTokenInfo("size.spotlight-bar-height", "dimension", "44px"),
        LPTokenInfo("size.spotlight-tile", "dimension", "56px"),
        LPTokenInfo("size.spotlight-cell", "dimension", "96px"),
        LPTokenInfo("size.spotlight-chat", "dimension", "320px"),
        LPTokenInfo("size.spotlight-accessory", "dimension", "28px"),
        LPTokenInfo("font.ui", "fontFamily", "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"Helvetica Neue\", Helvetica, Arial, Inter, sans-serif"),
        LPTokenInfo("font.display", "fontFamily", "\"Iowan Old Style\", \"Palatino Linotype\", Palatino, Georgia, P052, serif"),
        LPTokenInfo("font.mono", "fontFamily", "SFMono-Regular, ui-monospace, Menlo, Consolas, \"JetBrains Mono\", monospace"),
        LPTokenInfo("text.xs", "dimension", "11px"),
        LPTokenInfo("text.sm", "dimension", "12px"),
        LPTokenInfo("text.md", "dimension", "13px"),
        LPTokenInfo("text.lg", "dimension", "15px"),
        LPTokenInfo("text.xl", "dimension", "20px"),
        LPTokenInfo("text.xxl", "dimension", "28px"),
        LPTokenInfo("text.weight-regular", "fontWeight", "400"),
        LPTokenInfo("text.weight-medium", "fontWeight", "500"),
        LPTokenInfo("text.weight-semibold", "fontWeight", "600"),
        LPTokenInfo("text.weight-bold", "fontWeight", "700"),
        LPTokenInfo("text.leading-tight", "number", "1.2"),
        LPTokenInfo("text.leading-normal", "number", "1.45"),
        LPTokenInfo("motion.fast", "duration", "120ms"),
        LPTokenInfo("motion.normal", "duration", "200ms"),
        LPTokenInfo("motion.slow", "duration", "360ms"),
        LPTokenInfo("motion.ease-out", "cubicBezier", "cubic-bezier(0.2, 0.8, 0.2, 1)"),
        LPTokenInfo("motion.ease-spring", "cubicBezier", "cubic-bezier(0.34, 1.56, 0.64, 1)"),
        LPTokenInfo("motion.spring-sheen.frequency", "number", "1.2"),
        LPTokenInfo("motion.spring-sheen.damping", "number", "0.45"),
        LPTokenInfo("motion.spring-tilt.frequency", "number", "1.6"),
        LPTokenInfo("motion.spring-tilt.damping", "number", "0.6"),
        LPTokenInfo("motion.spring-jelly.frequency", "number", "2.2"),
        LPTokenInfo("motion.spring-jelly.damping", "number", "0.55"),
        LPTokenInfo("motion.spring-fly.frequency", "number", "2.3"),
        LPTokenInfo("motion.spring-fly.damping", "number", "0.8"),
        LPTokenInfo("motion.spring-radius.frequency", "number", "2.6"),
        LPTokenInfo("motion.spring-radius.damping", "number", "0.35"),
        LPTokenInfo("motion.spring-vx-lag.frequency", "number", "0.9"),
        LPTokenInfo("motion.spring-vx-lag.damping", "number", "0.9"),
        LPTokenInfo("motion.radius-detune", "number", "0.08"),
        LPTokenInfo("motion.slosh-frequency", "number", "1.3"),
        LPTokenInfo("motion.slosh-damping", "number", "0.16"),
        LPTokenInfo("motion.slosh-gain", "number", "0.0009"),
        LPTokenInfo("motion.slosh-max", "number", "0.5"),
        LPTokenInfo("motion.slosh-max-accel", "number", "12000"),
        LPTokenInfo("motion.slosh-lift", "number", "10"),
        LPTokenInfo("motion.slosh-shift", "number", "7"),
        LPTokenInfo("motion.slosh-velocity-ref", "number", "1200"),
        LPTokenInfo("motion.slosh-shear-gain", "number", "18"),
        LPTokenInfo("motion.slosh-shear-gamma", "number", "0.7"),
        LPTokenInfo("motion.jelly-max-scale", "number", "0.035"),
        LPTokenInfo("motion.jelly-max-skew", "number", "2.5"),
        LPTokenInfo("motion.tilt-max", "number", "3"),
        LPTokenInfo("motion.velocity-ref", "number", "2500"),
        LPTokenInfo("motion.drift-period", "duration", "45s"),
        LPTokenInfo("z.wallpaper", "number", "0"),
        LPTokenInfo("z.windows", "number", "100"),
        LPTokenInfo("z.menubar", "number", "600"),
        LPTokenInfo("z.menus", "number", "700"),
        LPTokenInfo("z.spotlight", "number", "800"),
    ]
}
